### ISSUE TITLE
dubbo demo运行问题

### ISSUE THREAD

**Issue by endy0114** [apache/servicecomb-pack#211]
1、jar冲突：log4j的两个桥接包冲突，guava16.1和20.0版本冲突，多个版本的netty冲突
2、dubbo2.6.1存在服务注册不到zookeeper上的bug

**Comment by WillemJiang** [comment]
@endy0114 你的问题解决了吗？ 
版本冲突可能是你的工程的问题，我们在集成测试的过程中没有发现这样的问题。
