### ISSUE TITLE
Dubbo事务补偿问题

### ISSUE THREAD

**Issue by airbaby** [apache/servicecomb-pack#223]
A系统调用B系统服务，A系统调用C系统服务, Saga-0.2.0版本；
1、A-B调用返回成功；
2、A-C调用返回失败；
出现问题：
B执行完后，C事务中断，C并“没有”调用自身补偿方法进行补偿，A也没有调用方法进行补偿？使用提供的Dubbo示例加入如下代码，也是同样的结果；

 @SagaStart
 @Compensable(compensationMethod="cancel")
 @Transactional(rollbackFor = Exception.class)
public void transfer(String from, String to, BigDecimal amount){
         //B服务Dubbo调用
         transBDubboService.transferBIn(to, 50);
        //C服务Dubbo调用
         transCDubboService.transferCIn(to, 50);
}

   //B服务Dubbo接口方法
   @Compensable(compensationMethod="cancel")
    @Transactional(rollbackFor = Exception.class)
    @Override
    public void transferBIn(String to, int amount) {
        LOG.info("C.Called,开始转入资金:"+amount);
        AccountPo accountPo= accountPoDao.queryByUserName(to);
        LOG.info("C.Called,开始转入资金:"+amount);
        //转入资金操作
        accountPo.setBalance(accountPo.getBalance().add(BigDecimal.valueOf(amount)));
        accountPoDao.updateByCond(accountPo);
    }

//C服务Dubbo接口方法
    @Compensable(compensationMethod="cancel")
    @Transactional(rollbackFor = Exception.class)
    @Override
    public void transferCIn(String to, int amount) {
        LOG.info("C.Called,开始转入资金:"+amount);
        AccountPo accountPo= accountPoDao.queryByUserName(to);
        //转入资金操作
        accountPo.setBalance(accountPo.getBalance().add(BigDecimal.valueOf(amount)));
        accountPoDao.updateByCond(accountPo);
    }

    //B和C服务补偿方法
    public void cancel(String to, int amount) {
        LOG.info("Called Cancel 开始取消转入转款:"+amount);
        AccountPo accountPo= accountPoDao.queryByUserName(to);
          //补偿,取消转入
         accountPo.setBalance(accountPo.getBalance().subtract(BigDecimal.valueOf(amount)));
         accountPoDao.updateByCond(accountPo);
        LOG.info("Called Cancel 补偿成功");
    }
![1531803341 1](https://user-images.githubusercontent.com/17855411/42797208-bdfff874-89c0-11e8-9d1b-b79c93f3d016.png)

**Comment by WillemJiang** [comment]
请问C事务中断是抛异常吗？因为你使用了@transactional， 如果服务抛异常， 对应的数据库提交动作就不会执行。 不调用C的补偿方法是正确的。 但是B的补偿方法是需要调用的， 这个在Dubbo示例的代码里面是能够正常执行的。 https://github.com/apache/incubator-servicecomb-saga/blob/master/acceptance-tests/acceptance-pack-dubbo-demo/src/test/resources/CExceptionWhenAbAc_scenario.feature

**Comment by airbaby** [comment]
是的，C事务抛出中断异常，不补偿是正常的； 但是B事务执行成功了，但是没有调用补偿(cancel方法)； 运行了dubbo demo方法，也并没有执行补偿，test-b表状态是run没有恢复为init；


执行地址格式： serviceInvoke/CExceptionWhenAbAc


     你好，我使用的dubbo版本是2.5.3；是不是dubbo版本或者部署alpha-server部署有问题；


 
在2018年7月17日 14:49，Willem Jiang<notifications@github.com> 写道：

请问C事务中断是抛异常吗？因为你使用了@transactional， 如果服务抛异常， 对应的数据库提交动作就不会执行。 不调用C的补偿方法是正确的。 但是B的补偿方法是需要调用的， 这个在Dubbo示例的代码里面是能够正常执行的。 https://github.com/apache/incubator-servicecomb-saga/blob/master/acceptance-tests/acceptance-pack-dubbo-demo/src/test/resources/CExceptionWhenAbAc_scenario.feature

**Comment by WillemJiang** [comment]
我们的验收测试用的是dubbo 2.6.1， 你看看能不升级一下。
还有你有没有试过 A-B, A最后抛出异常，看看B有没有回滚。

如果B能回滚，就需要确保调C出错的时候，异常能够在A方法中抛出。

**Comment by airbaby** [comment]
您好，已经调整到dubbo2.6.1版本，按照提供的dubbo-demo内所有jar包版本保持不变。应该与dubbo版本无关，仍然存在如下问题：
1、 alpha-server-0.2.0-exec.jar 采用MySQL，会报一个错误；
  如图3所示；


2、CExceptionWhenAbAc


  如图1和图2所示，b没有触发调用补偿方法(cancelRun)进行补偿；
public void cancelRun(InvokeContext invokeContext) {
LOG.info("B.cancel called");
doCancelBusi();
}
3、AExceptionWhenAb


  如图4所示，b没有触发调用补偿方法(cancelRun)；


 4、其他Ab, AbBc,BExceptionWhenAb, BExceptionWhenAb, CExceptionWhenAbBc，因为有@Transactional所以会回滚正常；
 
问题：补偿方法未被触发？
在2018年7月17日 15:12，李彪<javasun608139@163.com> 写道：
     是的，C事务抛出中断异常，不补偿是正常的； 但是B事务执行成功了，但是没有调用补偿(cancel方法)； 运行了dubbo demo方法，也并没有执行补偿，test-b表状态是run没有恢复为init；


执行地址格式： serviceInvoke/CExceptionWhenAbAc


     你好，我使用的dubbo版本是2.5.3；是不是dubbo版本或者部署alpha-server部署有问题；


 
在2018年7月17日 14:49，Willem Jiang<notifications@github.com> 写道：

请问C事务中断是抛异常吗？因为你使用了@transactional， 如果服务抛异常， 对应的数据库提交动作就不会执行。 不调用C的补偿方法是正确的。 但是B的补偿方法是需要调用的， 这个在Dubbo示例的代码里面是能够正常执行的。 https://github.com/apache/incubator-servicecomb-saga/blob/master/acceptance-tests/acceptance-pack-dubbo-demo/src/test/resources/CExceptionWhenAbAc_scenario.feature

**Comment by WillemJiang** [comment]
感觉你是用了MySQL的主从复制功能，这种情况下JPA不能创建临时表。

**Comment by WillemJiang** [comment]
@airbaby  Is there any update of this issue?

**Comment by WillemJiang** [comment]
这的确是个好消息， 现在系统已经投入生产了吗？
欢迎加入到Saga项目开发中来。

**Comment by WillemJiang** [comment]
Just close the issue as it is resolved.
