### ISSUE TITLE
是否可以事后进行向前恢复（重试），程序上下文如何恢复？

### ISSUE THREAD

**Issue by long187** [apache/servicecomb-pack#230]
当一个事务执行出错了， 采用了重试策略，比如说重试三次仍然出错，抛出异常，线程返回了。事后继续进行向前恢复（比如人工触发的），saga如何恢复到业务当时的执行断点，线程上下文如果恢复？

**Comment by WillemJiang** [comment]
线程调用返回，事务也就处理完了。 目前Saga不会和人工恢复有任何关联。

**Comment by long187** [comment]
由于缺乏隔离性，必然会出现小概率向后“补偿”或向前“重试”多次仍然不成功的情况，这时不可能无限重试，所以这时抛出异常线程返回。但这笔事务还是处于不一致的状态，alpha会定时轮训这些事务并触发向后“补偿”？但是不能触发向前重试对吧？

**Comment by WillemJiang** [comment]
重试也是有次数的， 如果重试不成功，最终还是要交给人工来进行相关的处理。

**Comment by long187** [comment]
最兜底的办法是工人处理，但人工处理最多是说处理无法重试成功的节点，不可能每个节点都人工处理，否则即使异常是小概率事件，交易量大的时候人工也是处理不过来的。
我的问题是：如果我走“向前重试”的策略，比如顺序执行A->B->C三个服务，如果B出错，重试3次不成功（比如数据被覆盖更新了，无法重试成功），然后人工处理了B的问题，B重试成功了，应该是要继续执行B后序逻辑。可以这样吗？如果可以，那么线程上下文如何恢复？

**Comment by WillemJiang** [comment]
如果涉及到了人工恢复，我们是无法恢复线程上下文的。

**Comment by long187** [comment]
好的，多谢。

**Comment by WillemJiang** [comment]
@long187  Do you mind close the issue if the answer is good enough?
BTW, the patch of [SCB-785](https://issues.apache.org/jira/browse/SCB-785) was applied into master branch.
