### ISSUE TITLE
docker-compose err:The image for the service you're trying to recreate has been removed

### ISSUE THREAD

**Issue by wNee** [apache/servicecomb-pack#334]
I want to test some demo, and when I run  ./saga-servicecomb-demo.sh up
Here come the error
Starting saga-servicecomb-demo:0.3.0-SNAPSHOT
Pulling alpha (alpha-server:0.3.0-SNAPSHOT)...

> ERROR: The image for the service you're trying to recreate has been removed.

 If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling alpha (alpha-server:0.3.0-SNAPSHOT)...
ERROR: pull access denied for alpha-server, repository does not exist or may require 'docker login'
So how can I run the demo in docker?

**Comment by WillemJiang** [comment]
I think you need to pull the servicecomb/alpha-server first.

**Comment by WillemJiang** [comment]
You can also build the docker image from the source with below command without running the test:
`mvn clean install -DskipTests=true -Pdemo,docker'
