### ISSUE TITLE
异步补偿性能问题

### ISSUE THREAD

**Issue by airbaby** [apache/servicecomb-pack#335]
异步补偿针对数据量比较大情况下，会存在时间延迟，需要做特殊处理；

**Comment by WillemJiang** [comment]
请问你说的异步补偿是什么？ 因为 Saga 是直接提交了， 补偿是在事务提交之后的修复操作，必定会存在延时情况。 你说的特殊处理是指？

**Comment by zhfeng** [comment]
异步补偿的意思是alpha server调用omega端的compensate方法？在现在的实现中，alpha server是通过定时event scan 查询到需要补偿的事件，然后调用对应的compensate方法，这个是同步调用，所以如果在compensate方法中有耗时的操作，会影响到性能。你指的特殊处理是什么？

**Comment by WillemJiang** [comment]
由于问题时间过长，我们先关闭问题，如果想继续讨论可以随时打开。
