### ISSUE TITLE
TxEvent table field compensationMethod varchar(256) is too small

### ISSUE THREAD

**Issue by jsbxyyx** [apache/servicecomb-pack#337]
Command, tcc_participate_event table is same.

example follow:
public com.changjiang.aiteam.common.basic.type.BasicLogicResult com.changjiang.aiteam.service.usercenter.logic.impl.UserRegisterServiceImpl.unregisterForCAS(com.changjiang.aiteam.common.basic.type.BasicLogicParam,java.lang.String,java.lang.String,java.lang.String)

**Comment by jsbxyyx** [comment]
Command table is same

**Comment by WillemJiang** [comment]
Ok, if you have a long package name , the compensationMethod could be very long.
I just create a [JIRA](https://issues.apache.org/jira/browse/SCB-1029) for it, do you mind submit a PR for it?  The fix could be much straightforward (just update the varchar number).

**Comment by zhfeng** [comment]
@WillemJiang is it OK to close this issue since you have merged the fix ?
