### ISSUE TITLE
pack-contract-grpc下面proto文件无法生存import org.apache.servicecomb.saga.pack.contract.grpc.TxEventServiceGrpc.TxEventServiceImplBase这个类。

### ISSUE THREAD

**Issue by hadoop835** [apache/servicecomb-pack#347]

**Comment by WillemJiang** [comment]
请问你是如何生成grpc文件的， 用maven命令还是通过IDE提供的插件。 
我这边用maven和 IDEA试了了一下都没有问题。

**Comment by WillemJiang** [comment]
You can use the IDEA  " maven -> generate sources and update folders" to generate the sources.
