### ISSUE TITLE
saga service stop?How to solve it( with spring cloud 2.0 test version)

### ISSUE THREAD

**Issue by xiawanyingtest** [apache/servicecomb-pack#350]
### 在spring cloud上不能补偿，saga服务端已经正常开启8080端口，saga服务里面的表，一点数据都没有，在启动文件上也加了@EnableOmega注解了
@Override
    public boolean test(Long id,int amount){

        return   transferMoney(id,amount);
    }
    @SagaStart(timeout=10)
    @Compensable
    public boolean transferMoney(Long id,int amount) {
        transferIn(id, amount);
        transferOut(id, amount);

        return  true;

    }

//    @Transactional(rollbackFor = Exception.class)
    @Compensable(timeout=5, compensationMethod="cancel")
    public boolean transferOut(Long id,int amount) {
        log.error("orderDetailRepository 操作---start\n");

        List<OrderDetail>  orderDetails= orderDetailRepository.findByOrderId(id);

        if (orderDetails.isEmpty()) return false;
        long quantity= orderDetails.get(0).getQuantity()+amount;

        int i=1/0;

        orderDetails.get(0).setQuantity(quantity);
        orderDetailRepository.save(orderDetails.get(0));
        log.error("orderDetailRepository 操作---end\n");

        return  true;

    }
//    @Transactional(rollbackFor = Exception.class)
    public boolean cancel(Long id,int amount) {
        log.error("orderDetailRepository 补偿操作---start\n");

        List<OrderDetail>  orderDetails= orderDetailRepository.findByOrderId(id);

        if (orderDetails.isEmpty()) return false;

        long quantity= orderDetails.get(0).getQuantity()-amount;

        orderDetails.get(0).setQuantity(quantity);
        orderDetailRepository.save(orderDetails.get(0));

        log.error("orderDetailRepository 补偿操作---end\n");

        return  true;
    }

//    @Transactional(rollbackFor = Exception.class)
    @Compensable(timeout=5, compensationMethod="cancelIn")
    public boolean transferIn(Long id,int amount) {

        log.error("orderRepository 操作---start\n");
        Optional<Order> optionalOrder= orderRepository.findById(id);

        if (!optionalOrder.isPresent())return  false;

        int quantity= optionalOrder.get().getQuantity()+amount;

        optionalOrder.get().setQuantity(quantity);
        orderRepository.save(optionalOrder.get());
        log.error("orderRepository 操作---end\n");

        return  true;
    }

//    @Transactional(rollbackFor = Exception.class)
    public boolean cancelIn(Long id,int amount) {
        log.error("orderRepository 补偿操作---start\n");

        Optional<Order> optionalOrder= orderRepository.findById(id);

        if (!optionalOrder.isPresent())return  false;

        int quantity= optionalOrder.get().getQuantity()-amount;

         optionalOrder.get().setQuantity(quantity);
         orderRepository.save(optionalOrder.get());
        log.error("orderRepository 补偿操作---end\n");

        return  true;
    }

**Comment by WillemJiang** [comment]
Can you check if already include the spring starter of Saga just like the demo we showed?
If you use Spring Boot, you need to build the Saga module yourself with the profile of spring-boot-2 just as the README said.

**Comment by WillemJiang** [comment]
ServiceComb Pack is using spring-boot-2 by default, so I close this issue.
Please reopen it if you still hit this kind of issue.
