### ISSUE TITLE
springboot1.5.17.RELEASE saga not work

### ISSUE THREAD

**Issue by Ouyangan** [apache/servicecomb-pack#354]
env:
```
springboot:1.5.17.RELEASE
orm: jpa
db:mysql
java -Dspring.profiles.active=mysql -jar alpha-server-0.3.0-SNAPSHOT-exec.jar
```
application.properties
```
app.datasource.first.url=jdbc:mysql://localhost/dt_1
app.datasource.first.username=root
app.datasource.first.password=root
app.datasource.second.url=jdbc:mysql://localhost/dt_2
app.datasource.second.username=root
app.datasource.second.password=root
app.datasource.second.max-total=30
server.context-path=/saga
logging.level.root=info
spring.jpa.show-sql=true
server.port=8083
spring.application.name=/sagaTransaction
alpha.cluster.address=127.0.0.1:8080
```
```
@EnableTransactionManagement
@EnableOmega
@SpringBootApplication
public class SagaApplication {
    public static void main(String[] args) {
        SpringApplication.run(SagaApplication.class, args);
    }
}
```
service code:
```
@Service
public class BuyService {
    @Autowired
    private AccountRepository accountRepository;
    @Autowired
    private GoodsRepository goodsRepository;

    @SagaStart(timeout = 10)
    public void buySuccess() {
        minusAmount(1, 1);
        minusGoods(1, 1);
    }

    /**
     * 扣减金额
     *
     * @param id
     * @param amount
     */
    @Compensable(timeout = 5, compensationMethod = "plusAmount")
    @Transactional(transactionManager = "firstTransactionManager", rollbackFor = Exception.class)
    public void minusAmount(long id, long amount) {
        accountRepository.minusAmount(id, amount);
    }

    @Transactional(transactionManager = "firstTransactionManager", rollbackFor = Exception.class)
    public void plusAmount(long id, long amount) {
        //todo 幂等处理
        accountRepository.plusAmount(id, amount);
    }

    /**
     * 扣减数量
     *
     * @param id
     * @param count
     */
    @Compensable(timeout = 5, compensationMethod = "plusGoods")
    @Transactional(transactionManager = "secondTransactionManager", rollbackFor = Exception.class)
    public void minusGoods(long id, long count) {
        goodsRepository.minusGoodsCount(id, count);
        //mock transaction fail
        int i = 10 / 0;
    }

    @Transactional(transactionManager = "secondTransactionManager", rollbackFor = Exception.class)
    public void plusGoods(long id, long count) {
        //todo 幂等处理
        goodsRepository.plusGoods(id, count);
    }

}

```
```
@Repository
public interface AccountRepository extends CrudRepository<Account, Long> {
    @Transactional
    @Modifying
    @Query(value = "update account set amount=amount-?2 where id=?1",
            nativeQuery = true)
    void minusAmount(long id, long minusAmount);

    @Transactional
    @Modifying
    @Query(value = "update account set amount=amount+?2 where id=?1",
            nativeQuery = true)
    void plusAmount(long id, long amount);
}
```
```
@Repository
public interface GoodsRepository extends CrudRepository<Goods, Long> {
    @Transactional
    @Modifying
    @Query(value = "update goods set quantity=quantity-?2 where id=?1",
            nativeQuery = true)
    void minusGoodsCount(long id, long minusCount);

    @Transactional
    @Modifying
    @Query(value = "update goods set quantity=quantity+?2 where id=?1",
            nativeQuery = true)
    void plusGoods(long id, long count);
}
```
application console:
```
Hibernate: update account set amount=amount-? where id=?
Hibernate: update goods set quantity=quantity-? where id=?
2018-12-18 00:47:02.619 ERROR 49627 --- [nio-8083-exec-1] o.a.s.s.o.transaction.SagaStartAspect    : Transaction e59d7b01-b225-49cf-b8a8-c2494e09b97e failed.
```
![image](https://user-images.githubusercontent.com/8913987/50101985-ee515600-025e-11e9-86a6-cd9d08fc5352.png)

**Comment by zhfeng** [comment]
Thanks @Ouyangan for being interested with the servicecomb saga.

In term of this issue, can you describe more about the failure ? what do you expect the result ? Do you see the compensate method is invoked ?

For the console log I can see the saga transaction is failed and I think it should invoke the compensate method. So you mean that the compensate does not happen ?

**Comment by WillemJiang** [comment]
@Ouyangan  Just a quick question, do you use the  MySQL cluster with the AlphaServer?

**Comment by Ouyangan** [comment]
> Thanks @Ouyangan for being interested with the servicecomb saga.
> 
> In term of this issue, can you describe more about the failure ? what do you expect the result ? Do you see the compensate method is invoked ?
> 
> For the console log I can see the saga transaction is failed and I think it should invoke the compensate method. So you mean that the compensate does not happen ?

mean that the compensate does not happen

here is project code,pls see "sagaTransaction" model.
https://github.com/Ouyangan/distributedTransactionDemo

**Comment by Ouyangan** [comment]
> @Ouyangan Just a quick question, do you use the MySQL cluster with the AlphaServer?

innodb_version	5.7.20
protocol_version	10
slave_type_conversions	
tls_version	TLSv1,TLSv1.1
version	5.7.20
version_comment	MySQL Community Server (GPL)
version_compile_machine	x86_64
version_compile_os	macos10.12

**Comment by WillemJiang** [comment]
> > @Ouyangan Just a quick question, do you use the MySQL cluster with the AlphaServer?
> 
> innodb_version	5.7.20
> protocol_version	10
> slave_type_conversions
> tls_version	TLSv1,TLSv1.1
> version	5.7.20
> version_comment	MySQL Community Server (GPL)
> version_compile_machine	x86_64
> version_compile_os	macos10.12

I don't  mean the version, I mean how many database instance do you have? We got the similar issue when the user has more than one db instance, and didn't enable the replication of temp db.

**Comment by WillemJiang** [comment]
After went through the code, I just found out the participate service and initial service are in the same processor, which means the transaction ID cannot be passed through the transport.  As the invocation is in the same thread, Saga processor can find out the Omega Context by default. 

I also checked saga version is 0.2.1 which has the [fix of @Transactional ](https://issues.apache.org/jira/browse/SCB-963). 

So we have to go back to the user story now.

If the first transaction is failed,  saga won't invoke it's compensation method as the local transaction should take care of it. If the first transaction is succeed and the second transaction is failed, the first transaction's compensation method will be invoked.

**Comment by Ouyangan** [comment]
> After went through the code, I just found out the participate service and initial service are in the same processor, which means the transaction ID cannot be passed through the transport. As the invocation is in the same thread, Saga processor can find out the Omega Context by default.
> 
> I also checked saga version is 0.2.1 which has the [fix of @Transactional ](https://issues.apache.org/jira/browse/SCB-963).
> 
> So we have to go back to the user story now.
> 
> If the first transaction is failed, saga won't invoke it's compensation method as the local transaction should take care of it. If the first transaction is succeed and the second transaction is failed, the first transaction's compensation method will be invoked.

Thank you for your prompt reply !
you mean Should I split the service into multiple services?  saga not support multi dataSource  in single application?
I test code ,the first transaction is success, second transaction is failed, but  first compensation method didn't invoked!

**Comment by zhfeng** [comment]
@Ouyangan well, if you are talking about the multi data sources in one application, I think you need the [JTA](https://en.wikipedia.org/wiki/Java_Transaction_API) solution here.

**Comment by WillemJiang** [comment]
The events in the db is not right, you can find the events of[ compensation scenario](https://github.com/apache/servicecomb-pack/blob/master/acceptance-tests/acceptance-pack-spring-demo/src/test/resources/pack_compensation_scenario.feature) here.
