### ISSUE TITLE
包引用问题

### ISSUE THREAD

**Issue by wz510172336** [apache/servicecomb-pack#358]
我的模块启动时报这个错误，我是按照saga-servicecomob-demo
例子来集成的，错误为：org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 23 in XML document from URL [jar:file:/app/app.jar!/BOOT-INF/lib/java-chassis-core-1.0.0.jar!/META-INF/spring/cse.bean.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 23; columnNumber: 120; cvc-elt.1: Cannot find the declaration of element 'beans'.
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]

**Comment by WillemJiang** [comment]
请问demo里面有这样的问题吗？如果没有建议对两个项目做一下对比，看看有什么不同的地方？

**Comment by WillemJiang** [comment]
@wz510172336 请问你的问题解决了吗？

**Comment by WillemJiang** [comment]
I'd like to close the issue as there is no feedback for one month.
