### ISSUE TITLE
Alpha集群如何保证高可用？

### ISSUE THREAD

**Issue by qcghdy** [apache/servicecomb-pack#359]

**Comment by WillemJiang** [comment]
目前Alpha Server 可以通过多实例（实例无状态）连接数据库集群的方式保证高可用。

**Comment by WillemJiang** [comment]
@qcghdy Can you close the issue if you don't have any further question about it?

**Comment by WillemJiang** [comment]
Hi, 
we introduced [a cluster service discovery management](https://github.com/apache/servicecomb-pack/blob/master/docs/user_guide.md#service-discovery-support) beside the Alpha Services,

So I close the issue,  please let us know if you have any other question about it.
