### ISSUE TITLE
服务一直注册不上

### ISSUE THREAD

**Issue by wz510172336** [apache/servicecomb-pack#362]
GET /v4/default/registry/existence?appId=default&type=microservice&serviceName=defaultMicroservice&env&version=1.0.0 fail, endpoint is 127.0.0.1:30100, message: Connection refused: /127.0.0.1:30100

**Comment by WillemJiang** [comment]
请把提供你使用的软件版本号信息，以及问题的上下文（是运行ServiceComb Demo，还是你自己改写的程序），单从描述来看有可能是服务中心 ServiceCenter没有启动。

**Comment by wz510172336** [comment]
你的项目能跑，目前是想按照你的demo，集成到我的springboot项目中，你有配套完整的软件依赖包吗？按照你servicecomb-demo项目的父pom及子pom依赖，全按我的层级关系加到了我项目pom文件中，目前serviercenter及postgrasql、alpha、都已经启动，但是我的项目微服务模块就是注册不上服务，我引用包是你项目install的pack包，依赖是：
 <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>spring-boot-starter-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-spring-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-transport-servicecomb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-connector-grpc</artifactId>
        </dependency>
    </dependencies>
    
    <dependencyManagement>
        <dependencies>
            
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.0.6.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            
            <dependency>
                <groupId>org.apache.servicecomb</groupId>
                <artifactId>java-chassis-dependencies</artifactId>
                <version>1.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-context</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-transaction</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-spring-tx</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-transport-resttemplate</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-transport-dubbo</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-transport-servicecomb</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-connector-grpc</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-spring-starter</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>omega-format</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>alpha-core</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>alpha-server</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>pack-contract-grpc</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicecomb.pack</groupId>
                <artifactId>pack-common</artifactId>
                <version>0.3.0-SNAPSHOT</version>
            </dependency>
</dependencyManagement>
报的错一直是：
io.grpc.StatusRuntimeException: UNAVAILABLE: NameResolver returned an empty list
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222) ~[grpc-stub-1.14.0.jar!/:1.14.0]
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203) ~[grpc-stub-1.14.0.jar!/:1.14.0]
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[grpc-stub-1.14.0.jar!/:1.14.0]
        at org.apache.servicecomb.pack.contract.grpc.TccEventServiceGrpc$TccEventServiceBlockingStub.onDisconnected(TccEventServiceGrpc.java:463) ~[pack-contract-grpc-0.3.0-SNAPSHOT.jar!/:0.3.0-SNAPSHOT]
        at org.apache.servicecomb.pack.omega.connector.grpc.tcc.GrpcTccClientMessageSender.onDisconnected(GrpcTccClientMessageSender.java:68) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar!/:0.3.0-SNAPSHOT]
        at org.apache.servicecomb.pack.omega.connector.grpc.core.PushBackReconnectRunnable.run(PushBackReconnectRunnable.java:52) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar!/:0.3.0-SNAPSHOT]
        at org.apache.servicecomb.pack.omega.connector.grpc.core.PendingTaskRunner$1.run(PendingTaskRunner.java:44) [omega-connector-grpc-0.3.0-SNAPSHOT.jar!/:0.3.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by WillemJiang** [comment]
这个错和之前的那个错不一样。 之前的错是和 ServiceComb 注册中心相关的，新的错是Alpha Server 连不上 Omega 实例。

**Comment by WillemJiang** [comment]
@wz510172336 请问问题解决了吗？

**Comment by WillemJiang** [comment]
长期没有回复，先关闭问题了。
