### ISSUE TITLE
如何连上你们开发的maven私库

### ISSUE THREAD

**Issue by nglj03** [apache/servicecomb-pack#369]
请问如何连上你们开发的maven私库？我现在在做servicecomb-pack 的手脚架，可是无法下载0.4.0-SNAPSHOT相关的依赖包，感谢

**Comment by WillemJiang** [comment]
The snapshot repo URL is here  https://repository.apache.org/content/repositories/snapshots/
We are doing the pack 0.3.0 release now, you should be able to access artifacts in 24 hours.

Please close the issue, if your question is answered.

**Comment by nglj03** [comment]
ok，thx

**Comment by WillemJiang** [comment]
@nglj03  FYI, We updated the README file for it in this #371.
