### ISSUE TITLE
我的服务模块连接不上alpha集群，以至于在全局事务时用restemplete 访问不了模块url

### ISSUE THREAD

**Issue by wz510172336** [apache/servicecomb-pack#372]
报这个错误：
2019-01-03 06:48:01.006 ERROR 40 --- [nio-8080-exec-1] o.a.s.s.o.transaction.SagaStartAspect    : Transaction 8018b128-a32b-4e08-befb-6c31c1262d0a failed.
is org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://account-service.servicecomb.io:8080/account/128/4": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)] with root cause
java.net.ConnectException: Connection refused (Connection refused
我代码是这样的：
@RestController
@Slf4j
public class MerchantAccountController {
    @Autowired
    private RestTemplate restTemplate;

    @Value("${account-service.service.address:http://account-service.servicecomb.io:8080}")
    private  String accoountUrl;

    @Value("${businesses-service.service.address:http://businesses-service.servicecomb.io:8080}")
    private  String businessesUrl;

    @SagaStart
    @PostMapping("/num/caculate/{num1}/{num2}")
    public void numCaculate(@PathVariable Integer num1, @PathVariable Integer num2) {
        log.info("saga事务start");
        //全局事务      restTemplate.postForEntity(accoountUrl+"/account/{num1}/{num2}",null,String.class,num1,num2);    restTemplate.postForEntity(businessesUrl+"/merchant/{num1}/{num2}",null,String.class,num1,num2);
        log.info("saga事务结束");
    }
}

**Comment by wz510172336** [comment]
alpha:
  cluster:
    address: alpha-server.servicecomb.io:8080
我在子模块中加了上述配置，用的saga-0.2.0 镜像,而且打上标记@enableomga后，应该在alpha中找得到instanceid，可是3个服务一个都没连接。不知道是不是grpc包引用问题还是Spring5.0.9和spring4.1.13与其兼容问题

**Comment by WillemJiang** [comment]
建议你使用最新发布的pack 0.3.0.  在这个版本中，我们已经把Spring boot版本升级到2.1 ， Spring 的版本也已经升级到5.0.9.  使用这个版本需要修改maven 包的group id和以及相关的包名。 你可以通过阅读[这段文档](https://github.com/apache/servicecomb-pack/blob/master/docs/user_guide_zh.md#%E5%BC%95%E5%85%A5pack%E7%9A%84%E4%BE%9D%E8%B5%96) 详细信息。

**Comment by WillemJiang** [comment]
@wz510172336  Any update of this issue? Did you resolve this issue?

**Comment by WillemJiang** [comment]
if you want to access alpha-server.servicecomb.io, we need to setup the dns for it. Current we just leverage docker-compose to do the job, if you don't start the services from the **docker-compose**, you may face that kind of issue. The workaround could be modifying the host file of you box, but it could be a challenge for you as there are too much details need to be taken care of.
