### ISSUE TITLE
omega-transport-feign配置错误

### ISSUE THREAD

**Issue by YangEdward** [apache/servicecomb-pack#376]
omega/omega-transport/omega-transport-feign/src/main/resources/META-INF/spring.factories
错误：
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
  org.apache.servicecomb.saga.omega.transport.feign.FeignAutoConfiguration
应该为：
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
  org.apache.servicecomb.pack.omega.transport.feign.FeignAutoConfiguration

**Comment by WillemJiang** [comment]
Thanks for pointing that out, I will commit quick fix for it shortly.

**Comment by WillemJiang** [comment]
@YangEdward Just send a PR #376 for it.

**Comment by WillemJiang** [comment]
The PR is merged into master branch.
