### ISSUE TITLE
How to run binaries against mysql

### ISSUE THREAD

**Issue by liubao68** [apache/servicecomb-pack#381]
I downloaded binary releases from https://apache.org/dyn/closer.cgi/servicecomb/servicecomb-pack/0.3.0/apache-servicecomb-pack-distribution-0.3.0-bin.zip and want to run it again mysql. 

I used this command but it does not work:

```
java -Dspring.profiles.active=mysql -D"spring.datasource.url=jdbc:mysql://localhost:3306/saga?useSSL=false" -Dspring.datasource.username=Y -Dspring.datasource.password=P -cp libs/mysql-connector-java-5.1.46.jar -jar alpha-server-0.3.0-exec.jar
```

Error is:

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under '' to com.zaxxer.hikari.HikariDataSource:

    Property: driverclassname
    Value: com.mysql.cj.jdbc.Driver
    Origin: "driverClassName" from property source "source"
    Reason: Failed to load driver class com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

Action:

Update your application's configuration

**Comment by WillemJiang** [comment]
You need to use the -Pmysql to compile the alpha server again to add the mysql connector dependency.

**Comment by liubao68** [comment]
Can we do it without compile the source?

**Comment by WillemJiang** [comment]
No, as we use the spring boot to generate the execution jar, if the class path is change we need to regenerate the jar again.  Maybe we can consider to create MySQL docker image. 

@liubao68  Could you close this issue once you get the answer.

**Comment by coolbeevip** [comment]
@liubao68 @WillemJiang 
We can use loads external jars support multiple database types
create libs directory in the  alpha-server-0.4.0-SNAPSHOT-exec.jar directory, copy  mysql-connector-java-8.0.15.jar to the libs directory And add config -Dloader.path=./libs to the command line, e.g.

```bash
java -Dloader.path=./libs -jar alpha-server-0.4.0-SNAPSHOT-exec.jar \
--spring.datasource.platform=mysql \
--spring.datasource.dataSourceClassName=com.mysql.jdbc.Driver \
--spring.datasource.url='jdbc:mysql://0.0.0.0:3306/saga?useUnicode=true&characterEncoding=utf-8&autoReconnect=true' \
--spring.datasource.username=saga-user \
--spring.datasource.password=saga-password \
--spring.profiles.active=prd
```

In order to external jars support need to modify alpha-server pom.xml use `ZIP` layout in maven plugin configuration, e.g

```
<plugin>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-maven-plugin</artifactId>
<configuration>
  <layout>ZIP</layout>
</configuration>
</plugin>
```

**Comment by WillemJiang** [comment]
@coolbeevip  Good shot.
Do you mind create a PR for it (with the pom changes and document)? I'd happy to merge it into master branch.

**Comment by coolbeevip** [comment]
> @coolbeevip Good shot.
> Do you mind create a PR for it (with the pom changes and document)? I'd happy to merge it into master branch.

Sure,I will be happy to do it

**Comment by WillemJiang** [comment]
Applied the patch #407 into master branch, so I just close this issue.
