### ISSUE TITLE
 NameResolver returned an empty list

### ISSUE THREAD

**Issue by luhuajiang** [apache/servicecomb-pack#393]
saga-spring-demo:
windows环境按照如下步骤启动报错：
1. mvn clean package -DskipTests

2. docker run -d -e "MYSQL_ROOT_PASSWORD=password" -e "MYSQL_DATABASE=saga" -e "MYSQL_USER=saga" -e "MYSQL_PASSWORD=password" -p 3306:3306 mysql/mysql-server:5.7

3. java -Dspring.profiles.active=mysql -D"spring.datasource.url=jdbc:mysql://192.168.99.100:3306/saga?useSSL=false" -jar alpha-server-0.4.0-SNAPSHOT-exec.jar
上面步骤没什么问题，运行java -Dserver.port=8081 -Dalpha.cluster.address=alpha-server.servicecomb.io:8080 -jar hotel-0.4.0-SNAPSHOT-exec.jar启动hotel这个service会出现错误提示： NameResolver returned an empty list。
${alpha_address}就是alpha-server.servicecomb.io这个地址吗？

**Comment by WillemJiang** [comment]
“alpha-server.servicecomb.io” 这个地址是需要dns解析了，如果你用docker compose启动的话，docker是会自动将这个名字和docker启动的进程地址绑定的，如果你是本地手工启动，建议换成能够访问的IP地址。

**Comment by WillemJiang** [comment]
Close the issue as there is no feedback for a month.
