### ISSUE TITLE
我的Saga事务不能保证完整性

### ISSUE THREAD

**Issue by rareman** [apache/servicecomb-pack#400]
根据tag:0.3.0用户指南写了个demo

```
  @SagaStart(timeout=10)
  public boolean transferMoney(String from, String to, int amount) {
    self.transferOut(from, amount);
    self.transferIn(to, amount);
  }

  @Compensable(timeout=5, compensationMethod="cancel")
  @Transactional
  public boolean transferOut(String from, int amount) {
    return true;
  }

  @Transactional
  public boolean cancel(String from, int amount) {
    return true;
  }

  @Compensable(timeout=5, compensationMethod="cancelTransferIn")
  @Transactional
  public void transferIn(String to, int amount) {
    try {
      TimeUnit.SECONDS.sleep(15L);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
    throw new IllegalArgumentException("transter fail");
  }

  public void cancelTransferIn(String to, int amount) {
    throw new IllegalArgumentException("transter cancel fail");
  }
```

- 问题1

    transferIn抛出异常后本地事务回滚，cancelTransferIn会再撤销

- 问题2

    cancel不会执行

**Comment by zhfeng** [comment]
Q1:

The cancelTransferIn throws the exception and this could cause the alpha to re-invoke the compensate method , also see the discuss on https://github.com/apache/servicecomb-pack/issues/346

Q2:

I can see that the Saga is marked with timeout=10, so I think the transaction will be rollbacked as the transferIn sleep for 15 second. How do you know the cancel method is not called ?

Anyway, can you share the whole project which we can be easy to reproduce these issues ? 
Thanks !

**Comment by WillemJiang** [comment]
we use transactional to make sure the local transaction is executed rightly. If the local transaction is failed,  Spring will rollback the local transaction, Omega don't need to call the compensation method of this local transaction.  As the whole saga transaction is failed, Omega need to call the compensation method of other succeed local transaction.

**Comment by rareman** [comment]
重试了问题2，compensationMethod可以执行；暂关闭该问题。
