### ISSUE TITLE
如何通过ES溯源业务流程

### ISSUE THREAD

**Issue by xiangyu345** [apache/servicecomb-pack#429]
怎样把全局事务ID与业务流关连？还有 aggregate 的实现

**Comment by coolbeevip** [comment]
我的做法是用zipkin做链路跟踪，而omega的事物id也是在http请求的header里

**Comment by xiangyu345** [comment]
觉得我的需求不太需要 zipkin，或者增加了复杂度。我比较关心的是业务可以从ES追踪溯源。 如果把订单id 放在事务id或可查询payload里， 有什么利弊

**Comment by WillemJiang** [comment]
现在根据Transaction ID 是可以建立调用关系图的，放在Header上面的好处是不用解析Payload包，如果遇到代理什么什么的还能透传。 订单ID这个和业务强相关，如果想做通用的追踪可能需要做一些扩展。

**Comment by WillemJiang** [comment]
由于ServiceComb Pack只截取方法的调用参数，并没有把相关业务payload放进来。
