### ISSUE TITLE
Do we need the web module in the main pom.xml???

### ISSUE THREAD

**Issue by asifdxtreme** [apache/servicecomb-pack#443]
https://github.com/apache/servicecomb-pack/blob/1ba63649fbe23d3830f8848cd68fc3340ca4b8b7/pom.xml#L41

**Comment by asifdxtreme** [comment]
cc @wujimin @liubao68 @WillemJiang

**Comment by WillemJiang** [comment]
Current we don't ship the web module in our release kit, it should be fine.
