### ISSUE TITLE
访问saga-frontend获取不到事务信息，报Access-Control-Allow-Origin错误

### ISSUE THREAD

**Issue by jinbinguo** [apache/servicecomb-pack#462]
环境: Win10,浏览器 chrome
浏览器F12查看具体错误信息：
Access to XMLHttpRequest at 'http://127.0.0.1:6090/saga/stats' from origin 'http://127.0.0.1:5200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by coolbeevip** [comment]
Start alpha with a parameter `alpha.rest.cors.enabled=true`
