### ISSUE TITLE
Project description not changed

### ISSUE THREAD

**Issue by liubao68** [apache/servicecomb-pack#467]
https://github.com/apache?utf8=%E2%9C%93&q=servicecomb&type=&language= 

Description is Apache ServiceComb Saga, need to be changed.

**Comment by liubao68** [comment]
It's better to add a short description, like java-chassis or service-center did.

**Comment by coolbeevip** [comment]
Do you mean the description attribute in the POM file?

**Comment by zhfeng** [comment]
I think it should be changed in the github servicecomb setting. But it seems we DO NOT have the permission to do these changes. @WillemJiang do we need to send this request to infrastructure team of  apache ?

**Comment by WillemJiang** [comment]
Now we don't have the right to update the project description, I will fill a Infra JIRA for it.

**Comment by WillemJiang** [comment]
The description was updated, so I close this issue.
