### ISSUE TITLE
可以自定义其他注册中心吗？

### ISSUE THREAD

**Issue by westboy** [apache/servicecomb-pack#474]
比如使用阿里开源nacos，如果自己集成这些需要注意那些问题

**Comment by cmonkey** [comment]
可以，目前注册中心主要是将alpha-server 的grpc port 信息写入到服务注册的metadata 中

你是要自己实现，还是等我来实现？

**Comment by westboy** [comment]
> 可以，目前注册中心主要是将alpha-server 的grpc port 信息写入到服务注册的metadata 中
> 
> 你是要自己实现，还是等我来实现？

官方要能支持那就太好了，能省去我们升级来回改麻烦

**Comment by WillemJiang** [comment]
你们的场景是什么样的？ 现在alpha的注册中心并没有特别限定。

**Comment by westboy** [comment]
@WillemJiang 我们也不是什么特别的场景，一个商城项目准备进行微服务改造，注册中心考虑使用nacos，所以针对注册中心这块请教下，
