### ISSUE TITLE
在只是用向后恢复的情况下，实现的服务和补偿方法是否必须要幂等

### ISSUE THREAD

**Issue by pengyu0929** [apache/servicecomb-pack#475]
我刚才看官方文档，里面有这样一段话：
`注意: 实现的服务使用相当的参数，实现的服务和补偿必须满足幂等的条件，同时建议使用Spring @Transactional标注提供本地事务保证。`

我的问题是：我现在只使用向后恢复，实现的服务和补偿方法是否可以不实现幂等。

我的理解是，保证幂等只是在使用向前恢复时，为了保证每次执行的结果都是一致的，是为了数据的最终一致性。而向后恢复，在服务出现异常时是直接执行补偿方法进行回滚的，不需要保证幂等。

**Comment by pengyu0929** [comment]
> 我刚才看官方文档，里面有这样一段话：
> `注意: 实现的服务使用相当的参数，实现的服务和补偿必须满足幂等的条件，同时建议使用Spring @Transactional标注提供本地事务保证。`
> 
> 我的问题是：我现在只使用向后恢复，实现的服务和补偿方法是否可以不实现幂等。
> 
> 我的理解是，保证幂等只是在使用向前恢复时，为了保证每次执行的结果都是一致的，是为了数据的最终一致性。而向后恢复，在服务出现异常时是直接执行补偿方法进行回滚的，不需要保证幂等。

**Comment by zhfeng** [comment]
补偿方法也可能被多次调用，所以也需要保证幂等性。

**Comment by pengyu0929** [comment]
在什么情况下补偿方法才会多次调用呢？

**Comment by zhfeng** [comment]
比如在alpha和omega之间的网络出现短时的故暂，而这时对补偿方法的调用返回network timeout，但omega端已经执行了补偿操作。这样的话，alpha还会再次尝试调用补偿方法。

**Comment by pengyu0929** [comment]
这样的话，我在子事务中如果有insert操作，这样就不能保证幂等，但这个insert操作时必不可少的。这种情况你们有考虑吗？
还有如果子事务中有update操作，如果出现异常，执行补偿方法，我如何将之前的数据恢复？（关键是如何获取update之前的数据）

**Comment by WillemJiang** [comment]
目前幂等还是需要在用户代码层面来保证，对于Omega和Alpha来说对不可能对了解业务实现细节。

**Comment by WillemJiang** [comment]
> 这样的话，我在子事务中如果有insert操作，这样就不能保证幂等，但这个insert操作时必不可少的。这种情况你们有考虑吗？
> 还有如果子事务中有update操作，如果出现异常，执行补偿方法，我如何将之前的数据恢复？（关键是如何获取update之前的数据）

对于这种问题不建议使用向前恢复，我觉得比较好的应对方法是直接失败，除非向后恢复操作。
