### ISSUE TITLE
请问servicecomb-saga支持哪些数据库？

### ISSUE THREAD

**Issue by pengyu0929** [apache/servicecomb-pack#477]
我看了你们的官方文档，没有找到这方面的介绍。从源码上，你们只给出了mysql和postgresql的脚本，你们是支持这个两个数据库吗？

**Comment by cmonkey** [comment]
对

**Comment by WillemJiang** [comment]
@pengyu0929 可以给我们提一个PR，修改一下README。

**Comment by pengyu0929** [comment]
能简单的说下为什么只支持这两种数据库吗？

**Comment by pengyu0929** [comment]
@WillemJiang 能简单的说下为什么只支持这两种数据库吗？

**Comment by WillemJiang** [comment]
我们是通过JPA支持的，理论上其他的数据库只要能对接JPA就可以使用。
不过后续Alpha这块可能会做一些调整，不排除使用no-sql数据库的可能性。

**Comment by pengyu0929** [comment]
@WillemJiang 我尝试了使用oracle数据库，在第一次执行时，可以插入TxEvent表中，但是表中始终只有一条数据（后一条数据会覆盖前面的），在之后的每次执行时，都不会将TxEvent插入。你们有过这种情况吗？是和eclipse jpa有关系吗？
