### ISSUE TITLE
请问你们支持链式调用的向后恢复吗？

### ISSUE THREAD

**Issue by pengyu0929** [apache/servicecomb-pack#482]
@WillemJiang 现在有一个场景：
A 调用 B ，B调用C，之后回到A。
如果在返回之后A出现异常，是否能够调用B和C的补偿方法呢？
我在B上添加了SagaStart和Compensable。

**Comment by zhfeng** [comment]
返回到A后，整个Saga事务已经结束了吧

**Comment by pengyu0929** [comment]
我在A上也添加了SagaStart，理论上，在回到A之后，如果A出现异常，omega
会向alpha发送abort时间，alpha在接受到这个事件之后，保存abort事件，之后查询TxStartEvent事件生成command对象，插入Command中，最后向调用补偿方法吗？

**Comment by pengyu0929** [comment]
@zhfeng 还有你们文档中写道：
> 注意: 若全局事务起点与子事务起点重合，需同时声明 @SagaStart 和 @Compensable 的注解
这句话怎么理解呢？

**Comment by WillemJiang** [comment]
> 我在A上也添加了SagaStart，理论上，在回到A之后，如果A出现异常，能够调用B和C的补偿方法吗？

如果在SagaStart定义的函数中出现异常是能够触发补偿方法回调的。

**Comment by WillemJiang** [comment]
> @zhfeng 还有你们文档中写道：
> 
> > 注意: 若全局事务起点与子事务起点重合，需同时声明 @SagaStart 和 @Compensable 的注解
> 
> 这句话怎么理解呢？

把全局事务@SagaStart和本地子事务@Compensable都放在一个函数中了。

**Comment by zhfeng** [comment]
那是否是下面这样的调用关系，我尝试用rest方式来调用B，C服务
```
public class A {
    @SagaStart
    @Compensable(compensationMethod = "cancel")
    @POST
    @Path("/serviceA")
    void serviceA(Order order) {
         restClient.invoke("http://localhost:8081/serviceB/", Order.class, order);
         save_order(order);
         throw new RuntimeException("cancel the order"); // throw the exception to abort the saga transaction
    }

    void cancel(Order order) {
         update_order(order, ORDER_STATUS.CANCEL);
    }
}

public class B {
       @POST
       @Path("/serviceB")
       @Compensable(compensationMethod="cancel“)
       void serviceB(Order order) {
            restClient.invoke("http://localhost/serviceC", Order.class, order);
       }
  
       void cancel(Order order) {
            log.info("serviceB order is cancelled");
       }
}

public class C {
       @POST
       @Path("/serviceC")
       @Compensable(compensationMethod="cancel“)
       void serviceC(Order order) {
            //handle order
       }

      void cancel(Order order) {
            log.info("serviceC order is cancelled");
       }
}
```

**Comment by zhfeng** [comment]
按这样的调用方式，如果A最后出现异常，会调用三个cancel方法来进行补偿

**Comment by pengyu0929** [comment]
@zhfeng 对于A我直接把它的事务交给Spring管理就行了。
还有就是这样调用方式，我发现在C出现异常时，可以调用B的补偿方法，但是A拿不到C的异常信息，
A拿到的异常信息：
`org.apache.servicecomb.pack.omega.transaction.OmegaException: transaction d17082be-f36a-4ed2-8148-e4bd6f8c153a is aborted`
这个是正常的吗？

**Comment by zhfeng** [comment]
如果A采用的是Spring事务管理的话，就不会参与到全局的Saga事务中。那只有B的补偿方法可以调用，最后A获得的异常信息也应该是B返回的。A和B之间采用的是什么调用方式？

**Comment by pengyu0929** [comment]
@zhfeng A和B之间使用Feign调用。
我测试了下，在A --> B --> C ，在C出现异常后，执行B的补偿方法（A的事务由Spring管理），但是A拿不到C的异常信息。
