### ISSUE TITLE
上万级TPS下，如何保证Alpha-Server和PGSQL的高可用及性能？

### ISSUE THREAD

**Issue by ghost0224** [apache/servicecomb-pack#483]
如题，PGSQL是否需要做分库？
Alpha-Server是否适合跨数据中心集群？我理解RPC走的是长连接，跨中心的通信可能不稳定？

**Comment by WillemJiang** [comment]
我们使用PG只是用来记录事件信息，只要定义和事件表hash的规则，是很容易提供支持分库分表支持的。 
只要分布式事务调用不是跨数据中心的，Alpha/Omega是不需要跨数据中心的。 目前跨数据中心调用的场景还很少，具体的优化可能要根据实际情况才能提出好的解决方案。

**Comment by ghost0224** [comment]
@WillemJiang 谢谢回复，我们目前的系统设计是数据按客户号做了分库，部署在同城双中心，特殊场景如转账，A客户到B客户可能存在跨中心的服务调用。这种场景请问该如何优化？
