### ISSUE TITLE
请问是否支持在一个方法中手动开启和结束SAGA事务吗？

### ISSUE THREAD

**Issue by ghost0224** [apache/servicecomb-pack#484]
如题

**Comment by zhfeng** [comment]
可以参考一下[SagaStartAnnotationProcessor](https://github.com/apache/servicecomb-pack/blob/master/omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/SagaStartAnnotationProcessor.java#L36)里面的方法。通过grpc sender向alpha发送SagaStartedEvent和SagaEndedEvent

**Comment by WillemJiang** [comment]
后续可以考虑是否把这部分的API暴露给客户， 现阶段我们是不希望用户关注这方面的实现（这部分实现有可能是会改变的）。

**Comment by zhfeng** [comment]
这对于不使用CDI的用户，可能有些帮助。
@ghost0224 可以简单描述一下你为什么需要这么做吗？

**Comment by ghost0224** [comment]
@zhfeng 有一些业务场景可能需要在SAGA事务开启前后做些处理，没关系我可以通过其他方式去实现。谢谢。

**Comment by WillemJiang** [comment]
@ghost0224 可否分享一下你的场景，如果是通用的，我们可以考虑修改pack的代码来方便更多的用户使用。

**Comment by zhfeng** [comment]
Yeah, I agree with @WillemJiang and we can consider to add some annotations such as PreSagaStart and PostSagaStart to achieve these requirements.
