### ISSUE TITLE
Alpha如何找到 多实例的omega客户端

### ISSUE THREAD

**Issue by wuyongCloud** [apache/servicecomb-pack#487]
服务基于spring-boot，部署在openshift中，没有使用discovery。假如发起事务回滚的实例在某一个点挂了无法执行补偿操作，alpha怎么找到其他实例执行回滚？

**Comment by WillemJiang** [comment]
每一个Omega向Alpha注册的时候都会把自己的ApplicationID以及InstanceID带上， 这样Alpha在进行补偿操作调用的时候会先找原来发送事件的Omega，如果找不到可以通过ApplicationID找同一应用的实例来进行补偿，如果通过ApplicationID还是找不到的话，就只能报错终止调用了。

**Comment by zhfeng** [comment]
@WillemJiang 那这样做的前提是每个Omega都应该保证是无状态(Stateless)和幂等(Idempotent) ?
@wuyongCloud 应用部署在openshift中，是要求能够scale up/down ?
