### ISSUE TITLE
数据库字段短 TxEvent instanceId 

### ISSUE THREAD

**Issue by wuyongCloud** [apache/servicecomb-pack#508]
instalceId=serviceName-ip,有可能会出现值的长度超过数据库定义的长度36

**Comment by WillemJiang** [comment]
如果在容器环境下， ip地址可能是会出现重复的， 我觉得可以考虑唯一ID，这样实例的长度也好控制。

**Comment by WillemJiang** [comment]
现在的解决方案可能是加一个函数判断instanceId是不是超长，给出相关的提示信息。
我在Apache JIRA上面建了这个[JIRA SCB-1495]( https://issues.apache.org/jira/browse/SCB-1495) 跟踪这个问题。

**Comment by WillemJiang** [comment]
@wuyongCloud JIRA上列出了解决方法，欢迎提交PR 。
