### ISSUE TITLE
如果把Alpha的功能设计成组件打包在应用里是否合理？

### ISSUE THREAD

**Issue by ghost0224** [apache/servicecomb-pack#509]
如果把Alpha的功能设计成组件打包在应用里是否合理？这样可以减少RPC调用，同时避免单点隐患。

**Comment by zhfeng** [comment]
那这样的应用是包含alpha的哪些功能？你的意思是应用同时作为全局事务的协调器？

**Comment by WillemJiang** [comment]
目前的设计是Alpha作为独立的协调器通过接收事务事件消息，来协调多个服务之间的事务调用。如果把Alpha的功能和应用代码放在一个进程就失去了我们解决分布式事务一致性的初衷了。

**Comment by ghost0224** [comment]
> 那这样的应用是包含alpha的哪些功能？你的意思是应用同时作为全局事务的协调器？

应该是 每个应用只负责协调在当前应用上发生分布式事务的场景，比如当前服务A要调用服务B时，此时A的代理来记录整个事务流水，并负责在调用B异常时触发A的反向交易；同样的，如果是从服务B发起时，则由B来记录整个事务流水并触发B的反向交易。我们项目目前也正在设计讨论分布式事务的解决方案，由于目标设计需要支持5万以上的TPS压力，所以想将协调服务分散在各个应用上去中心化，不知道这样设计是否有所弊端？或者我们没有考虑到的隐患？想请教下专家们，谢谢！

**Comment by cmonkey** [comment]
> > 那这样的应用是包含alpha的哪些功能？你的意思是应用同时作为全局事务的协调器？
> 
> 应该是 每个应用只负责协调在当前应用上发生分布式事务的场景，比如当前服务A要调用服务B时，此时A的代理来记录整个事务流水，并负责在调用B异常时触发A的反向交易；同样的，如果是从服务B发起时，则由B来记录整个事务流水并触发B的反向交易。我们项目目前也正在设计讨论分布式事务的解决方案，由于目标设计需要支持5万以上的TPS压力，所以想将协调服务分散在各个应用上去中心化，不知道这样设计是否有所弊端？或者我们没有考虑到的隐患？想请教下专家们，谢谢！

发起者crash了怎么办?

**Comment by WillemJiang** [comment]
@ghost0224 去中心化会带来管理和维护的问题，尤其是用户想知道所有的事务调用情况， 肯定不能一个服务一个服务去问。
