### ISSUE TITLE
k8s部署servicecomb，在补偿时，alpha报错

### ISSUE THREAD

**Issue by aresa7796** [apache/servicecomb-pack#518]
异常日志如下：

> 01:41:03.907 [pool-3-thread-1] INFO  org.apache.servicecomb.pack.alpha.core.CompositeOmegaCallback - Cannot find the service with the instanceId transferservice-10.10.0.86, call the other instance.
> 01:41:03.907 [pool-3-thread-1] ERROR org.apache.servicecomb.pack.alpha.core.PushBackOmegaCallback - Failed to compensate service [transferservice] instance [transferservice-10.10.0.86] with method [grabbit/cinit/transfer.CancelTransferOut], global tx id [6790be11-f47e-4e01-9f1a-ae222181bf35] and local tx id [e4b0062e-e494-4514-b5a3-a8032192040e]
> org.apache.servicecomb.pack.alpha.core.AlphaException: No such omega callback found for service transferservice
> 	at org.apache.servicecomb.pack.alpha.core.CompositeOmegaCallback.compensate(CompositeOmegaCallback.java:53) ~[alpha-core-0.5.0-SNAPSHOT.jar!/:0.5.0-SNAPSHOT]
> 	at org.apache.servicecomb.pack.alpha.core.PushBackOmegaCallback.compensate(PushBackOmegaCallback.java:46) ~[alpha-core-0.5.0-SNAPSHOT.jar!/:0.5.0-SNAPSHOT]
> 	at org.apache.servicecomb.pack.alpha.core.PushBackOmegaCallback.lambda$compensate$0(PushBackOmegaCallback.java:49) ~[alpha-core-0.5.0-SNAPSHOT.jar!/:0.5.0-SNAPSHOT]
> 	at org.apache.servicecomb.pack.alpha.core.PendingTaskRunner.lambda$run$0(PendingTaskRunner.java:39) ~[alpha-core-0.5.0-SNAPSHOT.jar!/:0.5.0-SNAPSHOT]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_212]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_212]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_212]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

查看发现在org.apache.servicecomb.pack.alpha.core.CompositeOmegaCallback的compensate方法中，callbacks是一个empty

**Comment by WillemJiang** [comment]
调用的服务实例有多少， 补偿的时候服务的实例还在吗？

**Comment by aresa7796** [comment]
我是用的go的client，用法不正确，现在好了
