### ISSUE TITLE
docker部署alpha时，host使用localhost，omega端报连接拒绝异常

### ISSUE THREAD

**Issue by pengyu0929** [apache/servicecomb-pack#541]
![QQ图片20190819170629](https://user-images.githubusercontent.com/47978636/63253075-bd209e00-c2a3-11e9-9cb2-1dca84ec3db8.png)

**Comment by coolbeevip** [comment]
你确定 alpha 的 gRPC 端口你配置的是8419？

**Comment by pengyu0929** [comment]
![QQ截图20190819171607](https://user-images.githubusercontent.com/47978636/63253781-10dfb700-c2a5-11e9-82d2-a1ecd9cd0031.png)
这是alpha的部分配置

**Comment by pengyu0929** [comment]
在omega端我们只配置了serviceId，用于在eureka上发现alpha，address的值为null

**Comment by pengyu0929** [comment]
我想问下，alpha的host必须要指定具体的ip吗？不能使用localhost吗？如果不可以，难道我换个容器就要重新指定ip？

**Comment by coolbeevip** [comment]
> 我想问下，alpha的host必须要指定具体的ip吗？不能使用localhost吗？如果不可以，难道我换个容器就要重新指定ip？

如果你不使用eureka是可以配置成localhost，如果你要用eureka，alpha需要告诉eureka自己的真实可访问地址，这样omega才能从eureka上获取到

**Comment by coolbeevip** [comment]
对于容器方式会比较复杂，你可以在启动的时候通过环境变量指定service.host，而不是在命令行指定server.host，我印象中k8s和mesos都有方法获取可访问的ip地址

**Comment by pengyu0929** [comment]
我将配置文件中的host改为具体的ip，在启动时报 address not available。
![WeChat Image_20190819174318](https://user-images.githubusercontent.com/47978636/63255774-e42d9e80-c2a8-11e9-82ee-fb6cd93cfc7d.png)

**Comment by coolbeevip** [comment]
你在eureka中可以看到alpha吗？

**Comment by pengyu0929** [comment]
可以的

**Comment by coolbeevip** [comment]
> 可以的

能看一下alpha的meta吗

**Comment by pengyu0929** [comment]
eureka:
  instance:
    metadataMap:
      srm-saga: ${ALPHA_SERVER_HOST}:${ALPHA_SERVER_PORT}

**Comment by pengyu0929** [comment]
`server:
  port: ${SERVER_PORT:8418}
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8425}
  endpoints:
    web:
      exposure:
        include: "*"

# 配置alpha端的端口号和地址
alpha:
  server:
    host: ${ALPHA_SERVER_HOST:localhost}
    port: ${ALPHA_SERVER_PORT:8419}
    serviceId: ${ALPHA_SERVER_SERVICE_ID:srm-saga}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://xxx:3306/srm_saga?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
eureka:
  instance:
    metadataMap:
      srm-saga: ${ALPHA_SERVER_HOST}:${ALPHA_SERVER_PORT}
logging:
  level:
    root: ${LOG_LEVEL:info}`
