### ISSUE TITLE
PackDubboConsumerFilter get null omegaContext

### ISSUE THREAD

**Issue by Fxdemon** [apache/servicecomb-pack#547]
PackDubboConsumerFilterh获取对象为null omegaContext  如何解决？

**Comment by WillemJiang** [comment]
How did you setup your project?
Current we just support to use spring-boot to start the application with OmegaContext.
Please check out the [saga-dubbo-demo](https://github.com/apache/servicecomb-pack/tree/master/demo/saga-dubbo-demo) for more information.

**Comment by Fxdemon** [comment]
Cannot inject transaction ID, as the OmegaContext is null.
使用saga-dubbo-demo没有问题 
我单独新建的项目  经过了一层代理对象处理发现OmegaContext对象为空

**Comment by WillemJiang** [comment]
We need to know how do you create the proxy for Dubbo.

**Comment by Fxdemon** [comment]
项目启动后 用rest 请求  dubbo泛化去调运 - dubbo提供者  ， 发现在请求的rest OmegaContext 对象是存在的 
@Autowired(
            required = false
    )
    private OmegaContext omegaContext;
断点到 PackDubboConsumerFilter类中为null

**Comment by Fxdemon** [comment]
发现通过xml配置文件发布的dubbo服务 在过滤器中可以获取到OmegaContext  
通过硬编码发布的服务  在服务消费的时候获取不到 OmegaContext = null

**Comment by WillemJiang** [comment]
It looks like we need to let spring create the filter for you, otherwise you need to inject  OmegaContext yourself through your hard code.

**Comment by Fxdemon** [comment]
public static void main(String[] args) {
        dubbo();
        SpringApplication.run(TestControllerApplication.class, args);
    }


    private static void dubbo() {
        ApplicationConfig application = new ApplicationConfig();
        application.setName("pack_dubbo_test");

        RegistryConfig registry = new RegistryConfig();
        registry.setAddress("zookeeper://127.0.0.1:2181");
//        registry.setGroup("1.0"); //这里加会注册不上
//        application.setRegistry(registry);

        ProviderConfig providerConfig = new ProviderConfig();
        providerConfig.setPort(20892);

        IGreetingService testService = new GreetingService();

        ServiceConfig<IGreetingService> service = new ServiceConfig<IGreetingService>();
        service.setApplication(application);
        service.setInterface("com.pactera.idbc.finance.service.IGreetingService");
        service.setRef(testService);
        service.setProvider(providerConfig);
//        service.setGroup("demo.samples");
        service.setRegistry(registry);
        service.export();

    }


这有发布的dubbo服务 在消费的时候  OmegaContext 为空 配置为xml 方式可以获取到 OmegaContext ？

**Comment by Fxdemon** [comment]
@WillemJiang 具体怎么处理 ？

**Comment by Fxdemon** [comment]
可以从spirng   SpringContextUtils implements ApplicationContextAware 中获取

**Comment by WillemJiang** [comment]
是的OmegaContext可以通过SpringApplicationContext获得，如果Dubbo服务不是由Spring创建的话，需要自己显示完成OmegaContext注入的工作。
