### ISSUE TITLE
关于servicecomb 框架 的问题以及开发者的建议！！！

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-pack#560]
看了一个多月的框架，我发现servicecomb 框架对 刚接触微服务的新手来讲，特别的不友好！
费那么多时间开发出来了，难道就不能出一点详细一点的文档嘛？官方文档开发指南简直可以忽略不计，对于新手来讲跟没有一样，很多类的引用，接口的引用，方法的引用全部都默认知道。。
很崩溃啊，看你们源代码，一点点扣，能出点详细点的开发入门文档嘛想知道

**Comment by coolbeevip** [comment]
不要激动，如果你描述出指南中哪个步骤无法执行下去，我想能够会得到更具体的帮助，这样也能帮助社区成长

**Comment by Fxdemon** [comment]
免费的枣 别嫌弃。

**Comment by WillemJiang** [comment]
首先ServiceComb Pack 现在没有全职的开发人员，绝大部分人都是用自己的业余时间在开发，希望你在抱怨的时候，多多包涵一下。如果对项目感兴趣，参与开源社区第一步，帮助完善文档。 
如果觉得文档不好，可以就具体的问题提问题，一味抱怨并不能解决问题。 我们会尽力帮助大家陈清问题，这也是交流学习提高的过程。 还有想了解代码的细节可以从我们的测试代码入手，里面有很多细节内容已经写在代码里面了。

**Comment by zhfeng** [comment]
可以先看一下example中的示例，这样可能会比较容易上手一点。当然，对于spring boot framework也需要了解一下。

**Comment by WillemJiang** [comment]
建议先从Demo代码入手，我们的demo都是有比较详细的说明，如果大家发现文档有问题可以随时指出我们会及时确认并修正的。
