### ISSUE TITLE
服用调用问题

### ISSUE THREAD

**Issue by pengyu0929** [apache/servicecomb-pack#562]
我们现在有三个服务作为客户端，调用顺序为 A -->B -->C，在C出现异常时，不能执行B的补偿方法，而 A --> B， A -- > C ，这种情况在C出异常时，是可以执行B的补偿方法的，这是为什么呢？是不是你们不支持这种调用方式 A-->B-->C.
ps：B -->C 是直接通过feign调用的

**Comment by zhfeng** [comment]
1. A, B,C 这三个服务的调用方法分别采用的什么注解 annotation ?
2. 在B->C的调用时候，global_transaction_id是否在header中传播propagation ?

可否共享一个简单的项目让我们可以重现这个问题？

**Comment by coolbeevip** [comment]
> 我们现在有三个服务作为客户端，调用顺序为 A -->B -->C，在C出现异常时，不能执行B的补偿方法，而 A --> B， A -- > C ，这种情况在C出异常时，是可以执行B的补偿方法的，这是为什么呢？是不是你们不支持这种调用方式 A-->B-->C.
> ps：B -->C 是直接通过feign调用的

按照我的理解，你的 A->B->C的方式不需分布式事务吧？C如果出现异常，这个异常不会逐级传递给A吗？就像

C catch exception ->  C 本地事务回滚 -> C throw excetion -> B catch exception  -> B 本地事务回滚 -> B throw exception -> A catch exception -> A 本地事务回滚

**Comment by zhfeng** [comment]
@coolbeevip 这可能是其中的一种情况吧。也有可能出现，A->B->C 调用都成功，但是在A中接下来的操作中业务逻辑判断需要进行回滚，整个事务都要做补偿。

**Comment by zhfeng** [comment]
这种chained invoking也是分布式事务中的一种类型。

**Comment by coolbeevip** [comment]
> @coolbeevip 这可能是其中的一种情况吧。也有可能出现，A->B->C 调用都成功，但是在A中接下来的操作中业务逻辑判断需要进行回滚，整个事务都要做补偿。



> @coolbeevip 这可能是其中的一种情况吧。也有可能出现，A->B->C 调用都成功，但是在A中接下来的操作中业务逻辑判断需要进行回滚，整个事务都要做补偿。

如果是在A调用B成功后在一个全局事务方法内出现异常，我想应该是可以正确补偿 B 和 C ，因为当 A 出现异常前，在Alpha中已经存在了两条成功的子事务 B 和 C，此时应该会对 B 和 C 进行补偿。

**Comment by coolbeevip** [comment]
> 这种chained invoking也是分布式事务中的一种类型。

谢谢提醒，我想我们需要一个验证一下

> @coolbeevip 这可能是其中的一种情况吧。也有可能出现，A->B->C 调用都成功，但是在A中接下来的操作中业务逻辑判断需要进行回滚，整个事务都要做补偿。

如果是在A调用B成功后在一个全局事务方法内出现异常，我想应该是可以正确补偿 B 和 C ，因为当 A 出现异常前，在Alpha中已经存在了两条成功的子事务 B 和 C，此时应该会对 B 和 C 进行补偿。

**Comment by zhfeng** [comment]
是的，前提是在B->C的调用时要把 gobal_transaction_id加到http header当中，并且在C的调用方法之前能够正确的加入全局事务中。所以我想看看他的代码是怎么写的。

**Comment by coolbeevip** [comment]
> 是的，前提是在B->C的调用时要把 gobal_transaction_id加到http header当中，并且在C的调用方法之前能够正确的加入全局事务中。所以我想看看他的代码是怎么写的。

哦，我还真没注意这种情况，如果 A，B，C 三个服务方法的注解采用如下方式，应该会自动传递 globalTxId吗？

A @SagaStart
B @Compensable
C @Compensable

我在 @Compensable的 TransactionContextHelper 中找到如下代码

```java
  protected void populateOmegaContext(OmegaContext context, TransactionContext transactionContext) {
    if (context.globalTxId() != null) {
      getLogger()
          .warn("The context {}'s globalTxId is not empty. Update it for globalTxId:{} and localTxId:{}", context,
              transactionContext.globalTxId(), transactionContext.localTxId());
    } else {
      getLogger()
          .debug("Updated context {} for globalTxId:{} and localTxId:{}", context,
              transactionContext.globalTxId(), transactionContext.localTxId());
    }
    context.setGlobalTxId(transactionContext.globalTxId());
    context.setLocalTxId(transactionContext.localTxId());
  }
```

**Comment by pengyu0929** [comment]
这个A服务：
```java
 @SagaStart
    @Override
    @Transactional
    public String booking(Booking booking) {
        System.out.println(booking.getName() + " : 开始预定。。。");
        carFeignClient.bookingCar(booking.getName(), booking.getCars(), booking.getRooms());
        System.out.println("预定结束。。。");
        return booking.getName() + " booking " + booking.getRooms() + " rooms and " + booking.getCars() + " cars OK";
    }
```
这个是B服务：
```java
 @Compensable(compensationMethod = "cancel")
    @Override
    @Transactional
    public CarBooking order(CarBooking booking, Integer rooms) {
        System.out.println(booking.getName() + " : 开始预定出租车。。。。");
        hotelFeignClient.bookingHotel("test", rooms);
        System.out.println(booking.getName() + " : 预定出租车成功 , 预定数量 ： ");
        return booking;
    }

    public void cancel(CarBooking booking, Integer rooms) {
        System.out.println("预定出租车出现异常，开始退订。。。");
        System.out.println("退订出租车成功，数量 ： ");
    }
```
这个是C服务：
```java
@Compensable(compensationMethod = "cancel")
    @Override
    @Transactional
    public HotelBooking order(HotelBooking booking) {
        System.out.println(booking.getName() + " ： 开始预定房间。。。");
        int i = 1 / 0;
        System.out.println(booking.getName() + " ： 预定房间成功，数量 ： " + booking.getRoomAmount());
        return booking;
    }

    public void cancel(HotelBooking booking) {
        System.out.println("预定房间出现异常，开始退订。。");
        System.out.println("退订房间成功，数量 ： " + booking.getRoomAmount());
    }
```

**Comment by coolbeevip** [comment]
> 这个A服务：
> 
> ```java
>  @SagaStart
>     @Override
>     @Transactional
>     public String booking(Booking booking) {
>         System.out.println(booking.getName() + " : 开始预定。。。");
>         carFeignClient.bookingCar(booking.getName(), booking.getCars(), booking.getRooms());
>         System.out.println("预定结束。。。");
>         return booking.getName() + " booking " + booking.getRooms() + " rooms and " + booking.getCars() + " cars OK";
>     }
> ```
> 
> 这个是B服务：
> 
> ```java
>  @Compensable(compensationMethod = "cancel")
>     @Override
>     @Transactional
>     public CarBooking order(CarBooking booking, Integer rooms) {
>         System.out.println(booking.getName() + " : 开始预定出租车。。。。");
>         hotelFeignClient.bookingHotel("test", rooms);
>         System.out.println(booking.getName() + " : 预定出租车成功 , 预定数量 ： ");
>         return booking;
>     }
> 
>     public void cancel(CarBooking booking, Integer rooms) {
>         System.out.println("预定出租车出现异常，开始退订。。。");
>         System.out.println("退订出租车成功，数量 ： ");
>     }
> ```
> 
> 这个是C服务：
> 
> ```java
> @Compensable(compensationMethod = "cancel")
>     @Override
>     @Transactional
>     public HotelBooking order(HotelBooking booking) {
>         System.out.println(booking.getName() + " ： 开始预定房间。。。");
>         int i = 1 / 0;
>         System.out.println(booking.getName() + " ： 预定房间成功，数量 ： " + booking.getRoomAmount());
>         return booking;
>     }
> 
>     public void cancel(HotelBooking booking) {
>         System.out.println("预定房间出现异常，开始退订。。");
>         System.out.println("退订房间成功，数量 ： " + booking.getRoomAmount());
>     }
> ```

就你这个例子来开，B不会被调用补偿方法，因为B的方法并没有调用成功，不需要补偿

**Comment by pengyu0929** [comment]
好的，谢谢了
