### ISSUE TITLE
globalTxId 为null，导致omega 不能向 alpha 发送事件

### ISSUE THREAD

**Issue by pengyu0929** [apache/servicecomb-pack#570]
场景：
A --> B  
A --> C
在进入 C 服务的时候，因为 globalTxId 为null，导致执行以下代码：
```java
public <T> Optional<AlphaResponse> doGrpcSend(MessageSender messageSender, T event, SenderExecutor<T> executor) {
    AlphaResponse response = null;
    try {
      long startTime = System.nanoTime();
      response = executor.apply(event);
      loadContext.getSenders().put(messageSender, System.nanoTime() - startTime);
    } catch (OmegaException e) {
      throw e;
    } catch (Exception e) {
      LOG.error("Retry sending event {} due to failure", event, e);
      loadContext.getSenders().put(messageSender, Long.MAX_VALUE);
    }
    return Optional.fromNullable(response);
  }
```
最终在挑选 sender 时，使用了默认的 sender ，抛出 `Failed to get reconnected sender, all alpha server is down.`
我的疑惑时，在 A 调用 B 的时候并没有出现任何错误，为什么在调用 C 的时候出现问题？
是因为 C 没有从请求头中取出 globalTxId 设置到 OmegaContext 中吗？
还有我们使用的是 0.4 版本，在 B 调用 C 时，使用了 Ribbon 的重试机制，但是我们通过查看日志，发现 B 第一次调用 C 的时候，Event 中的 globalTxId 就已经为 null 了

**Comment by coolbeevip** [comment]
> 在 B 调用 C 时，使用了 Ribbon 的重试机制，但是我们通过查看日志，发现 B 第一次调用 C 的时候，Event 中的 globalTxId 就已经为 null 了

你确定是 B调用C吗？我看你开头的场景说明是 A调用B，然后A再调用C

**Comment by pengyu0929** [comment]
写错了，是 A 调用 C

**Comment by WillemJiang** [comment]
A  重试调用C是不是通过另外一个线程来完成的， 如果是这样的话需要做一些额外的工作才能保证TransactionContext信息的传递。 
可否把调用的代码贴出看一下？

**Comment by pengyu0929** [comment]
TransactionContext 是 OmegaContext 吗？
还有刚才我们在 C 服务的日志中发现，请求头中并没有 globalTxId ，但是在调用 B 服务时，是没有问题的。
后来，重启了 C 服务，就成功了。但是在一段时间后就失败了
