### ISSUE TITLE
Failed to get reconnected sender, all alpha server is down

### ISSUE THREAD

**Issue by pengyu0929** [apache/servicecomb-pack#573]
我现在有两个问题：
1. 我发现有人在之前提出了和我现在一样的问题， #326 ，不知道你们是否修复？
2.有两个服务 A 、B，在A中有两个接口 A1、A2，B中有两个接口 B1、B2，在A1上没有添加@SagaStart注解，A2添加，B1、B2都添加了@Compensable注解；
请求三次，第一次请求A2-->B2，没有问题；
第二次请求A1-->B1，就出现了 `Failed to get reconnected sender, all alpha server is down`，此时omega将sender的value值设置成了 Long 的最大值；
第三次请求 A2-->B2，这时也出现了 `Failed to get reconnected sender, all alpha server is down`，
这时我发现 sender 的 value 值为 Long 的最大值，使用的是默认的sender；
以上情况，我认为 A1 没有添加 @SagaStart 注解出现问题是正常的，但是在之后调用 A2 时不应该出现 `Failed to get reconnected sender, all alpha server is down`;
之后我测试了一种情况，就是在请求A2-->B2，在B2向alpha发送事件时，我手动将alpha关闭，此时会抛出 `Failed to get reconnected sender, all alpha server is down` ，同时将sender的value值设置为Long的最大值。之后我重启alpha，再次请求A2-->B2，请求正常（sender的value值为0L）。
这种情况是为什么呢？是在omega重连alpha时将sender的value值重置了吗？可是我翻看源码并没找到相关的代码。

**Comment by WillemJiang** [comment]
我查了一下#326 的问题，[SCB-1011](https://issues.apache.org/jira/browse/SCB-1011) 显示这个问题还没有修复。 
没有修复是这种问题是和用户的使用方法有问题，在没有开启全局事务的情况下就发起请求。 
还有就是这个问题修复也比较简单就是Omega在发送消息的时候做一下数据检查就可以避免， 所以将其标记成为入门级bug fix，欢迎大家入手试一下提一个PR修复。

最后说一下Omega Sender 那块的代码写得比较精巧，因为没有处理好是数据包错误还是服务器连接错误， 导致最后因为Omega这块的修复需要把整个代码撸一遍才能完整解决，有兴趣的同学可以尝试做一下，我这边可以提供技术支持。

**Comment by pengyu0929** [comment]
好的，周末我提交一个pr

**Comment by WillemJiang** [comment]
Just merged the patch into master branch.
@pengyu0929  Please check out the PR and verify it.
