### ISSUE TITLE
feign版本兼容性

### ISSUE THREAD

**Issue by 706725357** [apache/servicecomb-pack#577]
omega-transport-feign-0.5.0用的是9.5.1的feign-core，spring-cloud-starter-openfeign版本如果在2.0.0以上的话就不支持了，编译的时候会出现找不到feignDecoder的错误

**Comment by WillemJiang** [comment]
我简单查了一下 omega-transport-feign， 其中并不直接依赖 feignDecoder， 可否能提供一个具体的工程，这样可以方便我们进行相关的分析工作。

**Comment by 706725357** [comment]
https://github.com/706725357/saga

**Comment by 706725357** [comment]
> 我简单查了一下 omega-transport-feign， 其中并不直接依赖 feignDecoder， 可否能提供一个具体的工程，这样可以方便我们进行相关的分析工作。

https://github.com/706725357/saga
根目录下的pom文件中更改openfeign版本至2.0.0以上后，contract就会出错了，去掉omega-transport-feign-0.5.0依赖后可以正常编译

**Comment by WillemJiang** [comment]
I just found this information on the feign github page. As we are target to support Spring Boot2 in ServiceComb Pack laster year, it's time to upgrade the Feign version to 10.x.  So I just create a [JIRA](https://issues.apache.org/jira/browse/SCB-1541) for it.

> Feign 10.x and above are built on Java 8 and should work on Java 9, 10, and 11. For those that need JDK 6 compatibility, please use Feign 9.x

**Comment by WillemJiang** [comment]
@706725357  Can you try the 0.6.0-SNAPSHOT in your project?

**Comment by 706725357** [comment]
> @706725357 Can you try the 0.6.0-SNAPSHOT in your project?
Yeah , I can. And I'v tried adding provided scope on feigin-core in omega-transport-feign，which works.

**Comment by WillemJiang** [comment]
@706725357  Do you mind close this issue?
