### ISSUE TITLE
请问，alpha-service的HA模式omega不能识别

### ISSUE THREAD

**Issue by tiangk** [apache/servicecomb-pack#600]
版本：0.5.0
启动alpha-service1 端口 9090，使用consul注册中心。启动omega，omega能过正常使用；
这时候启动alpha-service2 端口 9091，关闭之前的alpha-service1 ，这时候omega一直提示连接alpha-service1错误，就是说没有使用注册中心上新的服务接口。

请确认是我使用的版本不支持这种HA，还是我的配置有问题。

错误信息如下：
Connection refused: no further information: /0.0.0.0:9090

**Comment by tiangk** [comment]
同时启动alpha-service1 和alpha-service2， 然后启动omega，可以正常使用。
关闭alpha-service1， omega可用，但是一直报连接alpha-service1错误，这个不是很优雅。

**Comment by coolbeevip** [comment]
> 同时启动alpha-service1 和alpha-service2， 然后启动omega，可以正常使用。
> 关闭alpha-service1， omega可用，但是一直报连接alpha-service1错误，这个不是很优雅。

谢谢你的报告，这部分确实存在这个问题，检测到注册中心变化后需要通知Omega进行连接更新，我创建一个JIRA https://issues.apache.org/jira/browse/SCB-1608 跟进这个问题的解决，同时也欢迎提交PR。

**Comment by tiangk** [comment]
thank you！
