### ISSUE TITLE
如何查找需要手动补偿的所有事务

### ISSUE THREAD

**Issue by finnlee87** [apache/servicecomb-pack#603]
如何通过Alpha查找需要手动补偿的所有事务

**Comment by coolbeevip** [comment]
如果你使用的是状态机模式，那么可以通过访问控制台页面查询 https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md

**Comment by WillemJiang** [comment]
@coolbeevip  有对应的查询API吗？

**Comment by coolbeevip** [comment]
> @coolbeevip 有对应的查询API吗？

有翻页查询所有事务列表的API[1]，查询指定状态事务列表的API没有公开，目前只提供给UI使用。现阶段可以通过ES去查询

[1]https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/apis_zh.md

**Comment by finnlee87** [comment]
saga-ui  dashboard  一直报错 Property or field 'upTime' cannot be found on null

**Comment by coolbeevip** [comment]
> saga-ui dashboard 一直报错 Property or field 'upTime' cannot be found on null

你访问的地址是 http://localhost:8090/admin吗

> saga-ui dashboard 一直报错 Property or field 'upTime' cannot be found on null
你访问的地址是 http://localhost:8090/admin吗

**Comment by finnlee87** [comment]
/admin IndexController 91行 NullPointerException  
0.5.0 版本

**Comment by coolbeevip** [comment]
> /admin IndexController 91行 NullPointerException
> 0.5.0 版本

你能说明一下是如何启动Alpha的吗？或者提供一下命令行参数，另外能提供一下错误日志的堆栈信息吗

**Comment by finnlee87** [comment]
启动命令：
![startup](https://user-images.githubusercontent.com/8564495/69213738-f49f2f00-0b9f-11ea-941e-b0943ed9e38a.png)

错误堆栈
![errorstack](https://user-images.githubusercontent.com/8564495/69213767-097bc280-0ba0-11ea-8a5b-7e534943d4f4.png)

**Comment by finnlee87** [comment]
> > /admin IndexController 91行 NullPointerException
> > 0.5.0 版本
> 
> 你能说明一下是如何启动Alpha的吗？或者提供一下命令行参数，另外能提供一下错误日志的堆栈信息吗

**Comment by coolbeevip** [comment]
你用的是windows操作系统吗？

**Comment by finnlee87** [comment]
> 你用的是windows操作系统吗？
是的，但是我试了你提供的docker image 也有同样问题

**Comment by finnlee87** [comment]
> 你用的是windows操作系统吗？


是的，但是我试了你提供的docker image 也有同样的问题

**Comment by WillemJiang** [comment]
> > 你用的是windows操作系统吗？
> 
> 是的，但是我试了你提供的docker image 也有同样的问题

你用的浏览器是什么样的？

**Comment by coolbeevip** [comment]
> > 你用的是windows操作系统吗？
> 
> 是的，但是我试了你提供的docker image 也有同样的问题
 
根据错误日志判断，应该是下边的代码出现的问题

```java
    systemInfoDTO.setSystemLoad(Math.round(
        metricsEndpoint.metric("system.load.average.1m", null).getMeasurements().get(0).getValue()
            .floatValue() * 100) / (float)100);
```

metricsEndpoint 使用的是 spring boot actuator 组件，我不确定是否会因为操作系统问题导致 system.load.average.1m 获取不到，也许需要做一下容错处理

**Comment by coolbeevip** [comment]
> > 你用的是windows操作系统吗？
> 
> 是的，但是我试了你提供的docker image 也有同样的问题

 你的JDK版本是？

**Comment by coolbeevip** [comment]
@finnlee87 我想我知道大概什么原因了，spring boot actuator 的指标监控依赖的是 [micrometer](https://github.com/micrometer-metrics)，我在官网没有找到关于 system.load.average.1m 的说明，但是我找到了它的一个测试用例，我想应该是基于window部署的时候获取不到这个这标志

https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java#L32

**Comment by finnlee87** [comment]
> > > 你用的是windows操作系统吗？
> > 
> > 
> > 是的，但是我试了你提供的docker image 也有同样的问题
> 
> 你的JDK版本是？


amazon corretto 8

**Comment by finnlee87** [comment]
> @finnlee87 我想我知道大概什么原因了，spring boot actuator 的指标监控依赖的是 [micrometer](https://github.com/micrometer-metrics)，我在官网没有找到关于 system.load.average.1m 的说明，但是我找到了它的一个测试用例，我想应该是基于window部署的时候获取不到这个这标志
> 
> https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java#L32


那为什么你提供的那个docker image也是同样的问题呢

**Comment by finnlee87** [comment]
> > > 你用的是windows操作系统吗？
> > 
> > 
> > 是的，但是我试了你提供的docker image 也有同样的问题
> 
> 你用的浏览器是什么样的？


chrome

**Comment by coolbeevip** [comment]
> > @finnlee87 我想我知道大概什么原因了，spring boot actuator 的指标监控依赖的是 [micrometer](https://github.com/micrometer-metrics)，我在官网没有找到关于 system.load.average.1m 的说明，但是我找到了它的一个测试用例，我想应该是基于window部署的时候获取不到这个这标志
> > https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java#L32
> 
> 那为什么你提供的那个docker image也是同样的问题呢

你的 docker 运行环境是什么样子的？

**Comment by coolbeevip** [comment]
I just create a JIRA https://issues.apache.org/jira/browse/SCB-1611 tracking the issue

**Comment by finnlee87** [comment]
请问这个错是为什么 为什么说ES没有权限呢
![2019-11-21_151553](https://user-images.githubusercontent.com/8564495/69315655-f6392780-0c71-11ea-97d5-6ef6ad06757a.png)

**Comment by coolbeevip** [comment]
> 请问这个错是为什么 为什么说ES没有权限呢
> ![2019-11-21_151553](https://user-images.githubusercontent.com/8564495/69315655-f6392780-0c71-11ea-97d5-6ef6ad06757a.png)

我测试的时候使用的是  elasticsearch 6.6.2
我没有遇到过这种错误，也许你可以给 https://github.com/elastic/elasticsearch 提交一个问题

**Comment by finnlee87** [comment]
> > 请问这个错是为什么 为什么说ES没有权限呢
> > ![2019-11-21_151553](https://user-images.githubusercontent.com/8564495/69315655-f6392780-0c71-11ea-97d5-6ef6ad06757a.png)
> 
> 我测试的时候使用的是 elasticsearch 6.6.2
> 我没有遇到过这种错误，也许你可以给 https://github.com/elastic/elasticsearch 提交一个问题，或者检查以下这个文档中的说明 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/disk-allocator.html


谢谢 我再测试一下

**Comment by coolbeevip** [comment]
> @finnlee87 我想我知道大概什么原因了，spring boot actuator 的指标监控依赖的是 [micrometer](https://github.com/micrometer-metrics)，我在官网没有找到关于 system.load.average.1m 的说明，但是我找到了它的一个测试用例，我想应该是基于window部署的时候获取不到这个这标志
> 
> https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java#L32

Fixed #604

**Comment by coolbeevip** [comment]
> > @finnlee87 我想我知道大概什么原因了，spring boot actuator 的指标监控依赖的是 [micrometer](https://github.com/micrometer-metrics)，我在官网没有找到关于 system.load.average.1m 的说明，但是我找到了它的一个测试用例，我想应该是基于window部署的时候获取不到这个这标志
> > https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java#L32
> 
> 那为什么你提供的那个docker image也是同样的问题呢

0.7.0-SNAPSHOT 版本解决了此问题，你可以使用一下脚本试试

```
docker run \
  -p 8080:8080 \
  -p 8090:8090 \
  -p 5432:5432 \
  coolbeevip/servicecomb-pack:0.7.0-all-in-one
```
