### ISSUE TITLE
admin问题

### ISSUE THREAD

**Issue by tnessn** [apache/servicecomb-pack#613]
使用的版本为0.6.0-SNAPSHOT
有两个问题：
1.管理台页面404
![image](https://user-images.githubusercontent.com/5991683/70984817-1aafe480-20f6-11ea-8932-047a1d8e192d.png)

2.事务请求成功了，数据库也有数据，可是没有在管理台体现出来
![image](https://user-images.githubusercontent.com/5991683/70985010-6a8eab80-20f6-11ea-82fe-4fd76859af4c.png)
![image](https://user-images.githubusercontent.com/5991683/70985043-74b0aa00-20f6-11ea-858b-bcc44d90febb.png)

**Comment by coolbeevip** [comment]
AlphaUI only works in state machine mode
https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md

**Comment by tnessn** [comment]
> AlphaUI only works in state machine mode
> https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md

那就是分布式事务没问题了？

**Comment by coolbeevip** [comment]
> > AlphaUI only works in state machine mode
> > https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md
> 
> 那就是分布式事务没问题了？

I think so.

**Comment by tnessn** [comment]
> > > AlphaUI only works in state machine mode
> > > https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md
> > 
> > 
> > 那就是分布式事务没问题了？
> 
> I think so.

ok thanks

**Comment by WillemJiang** [comment]
@tnessn do you mind close this issue if the question is anwered.

**Comment by coolbeevip** [comment]
I created a JIRA https://issues.apache.org/jira/browse/SCB-1688 for prompt information when accessing Alpha UI in non-state machine mode
