### ISSUE TITLE
显式传递事务上下文文档有误

### ISSUE THREAD

**Issue by tnessn** [apache/servicecomb-pack#614]
![image](https://user-images.githubusercontent.com/5991683/70986131-46cc6500-20f8-11ea-9daa-6cec615d2f88.png)

红框的地方这个类没有实现序列化，我看文档cancel方法要求每个参数都需要序列化，所以报错

**Comment by WillemJiang** [comment]
这个方法是一个示例，TransactionContext的实例是需要实现序列化的方法。 
能详细描述一下你所遇到的的错误信息吗？

**Comment by chanjarster** [comment]
嗯，我觉得不是文档有误，而是`TransactionContext`的确是应该`Serializable`的。

**Comment by chanjarster** [comment]
建了个PR：https://github.com/apache/servicecomb-pack/pull/617

**Comment by WillemJiang** [comment]
代码已合入，@tnessn麻烦更新试用一下。
