### ISSUE TITLE
TransactionContextProperties接口

### ISSUE THREAD

**Issue by tnessn** [apache/servicecomb-pack#619]
TransactionContextProperties接口没有set方法，还得自己写个类有点麻烦
![image](https://user-images.githubusercontent.com/5991683/71228152-5c21d900-231c-11ea-98a2-0940ee3de32e.png)

**Comment by chanjarster** [comment]
文档里是这么写的：

```java
public class BarCommand {}
public class BarCommandWithTxContext 
  extends BarCommand implements TransactionContextProperties {
  // setter getter for globalTxId
  // setter getter for localTxId
}
```
可以看到TransactionContextProperties是用来给你原来的对象增加事务上下文信息的，看你的代码应该直接使用TransactionContext会更适合一些。

**Comment by tnessn** [comment]
> 文档里是这么写的：
> 
> ```java
> public class BarCommand {}
> public class BarCommandWithTxContext 
>   extends BarCommand implements TransactionContextProperties {
>   // setter getter for globalTxId
>   // setter getter for localTxId
> }
> ```
> 
> 可以看到TransactionContextProperties是用来给你原来的对象增加事务上下文信息的，看你的代码应该直接使用TransactionContext会更适合一些。

之前就是因为TransactionContext没序列化才使用这种方式的

**Comment by chanjarster** [comment]
TransactionContext序列化问题已经在 PR #617 里解决了，你可以试试

**Comment by WillemJiang** [comment]
@tnessn 代码已经合入到master branch，可以在你的pom[配置SNAPSHOT库](https://github.com/apache/servicecomb-pack#get-the-latest-version)，使用0.6.0-SNAPSHOT来验证。
