### ISSUE TITLE
Failed to get reconnected sender, all alpha server is down

### ISSUE THREAD

**Issue by Jakty** [apache/servicecomb-pack#634]
环境：spring boot , spring cloud，注册中心用的是eureka
问题：
现在有两个微服务A和B，两个服务都添加了Omega-transport-feign的依赖版本(所有的版本均为0.5.0)。问题点出在5上
1. 在A服务上添加@SagaStart注解和@Compensable注解时访问A服务一切正常；
2. 也在B服务上添加@SagaStart注解和@Compensable注解时访问B服务也一切正常；
3. 在A、B服务都没有添加@SagaStart注解和@Compensable注解，A通过openFeign来调用B服务也正常；
4. 在A服务在A服务上添加@SagaStart注解，但没有加@Compensable注解；B服务@SagaStart注解和@Compensable注解这两个注解都没有添加；A通过openFeign来调用B服务正常；
5 . 在A服务在A服务上添加@SagaStart注解，但没有加@Compensable注解；B服务上添加@Compensable注解，但没有加@Compensable注解这两个注解都没有添加；A通过openFeign来调用B服务则报错；
   错误如下：
        A服务报错：java.net.socketTimeoutExcption: Read timed out 
        B服务报错：org.apache.servicecomb.pack.omega.transation.OmegaException: Failed to get reconnected sender, all alpha server is down.

**Comment by Jakty** [comment]
> 环境：spring boot , spring cloud，注册中心用的是eureka
> 问题：
> 现在有两个微服务A和B，两个服务都添加了Omega-transport-feign的依赖版本(所有的版本均为0.5.0)。问题点出在5上
> 
> 1. 在A服务上添加@SagaStart注解和@Compensable注解时访问A服务一切正常；
> 2. 也在B服务上添加@SagaStart注解和@Compensable注解时访问B服务也一切正常；
> 3. 在A、B服务都没有添加@SagaStart注解和@Compensable注解，A通过openFeign来调用B服务也正常；
> 4. 在A服务在A服务上添加@SagaStart注解，但没有加@Compensable注解；B服务@SagaStart注解和@Compensable注解这两个注解都没有添加；A通过openFeign来调用B服务正常；
> 5 . 在A服务在A服务上添加@SagaStart注解，但没有加@Compensable注解；B服务上添加@Compensable注解，但没有加@Compensable注解这两个注解都没有添加；A通过openFeign来调用B服务则报错；
>    错误如下：
>    A服务报错：java.net.socketTimeoutExcption: Read timed out
>    B服务报错：org.apache.servicecomb.pack.omega.transation.OmegaException: Failed to get reconnected sender, all alpha server is down.

**Comment by Jakty** [comment]
和# [583](https://github.com/apache/servicecomb-pack/issues/583) 问题相似，但就是提示失败，已添加Omega-transport-feign包

**Comment by WillemJiang** [comment]
你说的5情况有点没有看懂， B服务到底添加了@Compensable注解了吗？
A服务的错误是调用B服务出的错 还是连接Alpha Server出的错？

**Comment by WillemJiang** [comment]
@Jakty  可否查看一下服务B的日志，我感觉是配置问题，Omega Agent出错，导致Alpha连接失败。

**Comment by Jakty** [comment]
@WillemJiang 
你说的5情况有点没有看懂， B服务到底添加了@Compensable注解了吗？
A服务的错误是调用B服务出的错 还是连接Alpha Server出的错？

第5种情况的B服务上有添加@Compensable注解，
在启动服务A和服务B时，在alpha server 的日志上有看到服务A和服务B有连接到alpha server上

**Comment by Jakty** [comment]
@WillemJiang 问题已找到
原因是在B服务的pom.xml中引入了Omega-transport-feign的拦截器，但实际上没有把Omega-transport-feign的jar包引入到B服务中。刷新idea的maven后，看到Omega-transport-feign的jar，再启动就OK了。

多谢你的解答！！

**Comment by WillemJiang** [comment]
估计还是Omega构建包的时候出错了， 但是由于Omega并没有区分Exception的类型，导致Exception被认为是Alpha Server连接的问题。
