### ISSUE TITLE
关于SAGA模式设计上的问题

### ISSUE THREAD

**Issue by WindyDovs** [apache/servicecomb-pack#635]
基于 0.5.0 版本的 SAGA 注解功能，查看了 alpha server 的源码，发现是使用 EventScanner 进行定时扫描的，其中的内容包括超时处理，补偿处理等。
  private void pollEvents() {
    scheduler.scheduleWithFixedDelay(
        () -> {
          // only pull the events when working in the master mode
          if(nodeStatus.isMaster()){
            updateTimeoutStatus();
            findTimeoutEvents();
            abortTimeoutEvents();
            saveUncompensatedEventsToCommands();
            compensate();
            updateCompensatedCommands();
            deleteDuplicateSagaEndedEvents();
            updateTransactionStatus();
          }
        },
        0,
        eventPollingInterval,
        MILLISECONDS);
  }

个人对此处感觉比较迷惑，不知道是否没理解到位，特提出此咨询：
补偿操作中对 command 的 pending 状态设置后，若在发送补偿前 server 崩溃，重启后是否就无法恢复事务了？
对 txtimeout 表的操作同理，若刚把 TimeOut 表的记录设置为 PENDING，alpha挂掉，那么该超时事件可能永远无法处理？
此处的众多处理是根据 eventPollingInterval 进行轮询串行处理的，此处的处理每次只处理一个超时、补偿的操作，在出现较高并发，或存在某些补偿服务的调用时间过长时，是否会导致补偿操作的严重滞后？

**Comment by WillemJiang** [comment]
EventScanner 的解决办法是有一定局限性的， 在0.5.0中，我们提供了一个基于Actor的状态机模型来处理事件信息，你可以通过这个[文档](https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md)获取更详细的信息。

**Comment by WindyDovs** [comment]
> EventScanner 的解决办法是有一定局限性的， 在0.5.0中，我们提供了一个基于Actor的状态机模型来处理事件信息，你可以通过这个[文档](https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md)获取更详细的信息。

好的，我看过了这部分。
还有些疑问，有劳指教：
1、后续 pack 在 SAGA 模式是否主推状态机模式？
2、状态机模式下，有三个应用，若存在 A->B，B->C 这种交易链路，是否需要在 A 与 B 应用中各新建一个任务编排逻辑，A 应用的状态机执行的是调用 B，B 应用的状态机执行的是 B 调用 C，而他们之间一样可以像注解模式那样对全局事务ID进行传播，绑定事务上下文？

**Comment by zhfeng** [comment]
状态机模型是在Alpha server端来使用的，目的也是为了协调Saga transaction的各个参与者，决定是否进行补偿操作。A，B和C这三个应用作为事务的参与者，是不需要了解Alpha端的实现机制的，只需要根据收到的event来做相应的操作。全局事务Id可以在服务调用过程中进行传播，Alpha根据这个Id来区分不同的事务。

**Comment by WindyDovs** [comment]
> 状态机模型是在Alpha server端来使用的，目的也是为了协调Saga transaction的各个参与者，决定是否进行补偿操作。A，B和C这三个应用作为事务的参与者，是不需要了解Alpha端的实现机制的，只需要根据收到的event来做相应的操作。全局事务Id可以在服务调用过程中进行传播，Alpha根据这个Id来区分不同的事务。

原来如此，是我理解有误了，非常感谢。
