### ISSUE TITLE
saga can not execute compensationMethod

### ISSUE THREAD

**Issue by gjguanjie** [apache/servicecomb-pack#637]
when local transaction occur exception,  TxAbortedEvent will be sent.  thus, local TxEndedEvent can not be sent to alpha server. But, alpha scheduler just to find TxEndedEvent. 

however, among database table txevent can not find TxEndedEvent (just as  in method EventScanner#saveUncompensatedEventsToCommands() {
    eventRepository.findFirstUncompensatedEventByIdGreaterThan(nextEndedEventId, 
    TxEndedEvent.name()
})

"findFirstUncompensatedEventByIdGreaterThan" method can not find any TxEndedEvent Data.

1)  so. I think that "findFirstUncompensatedEventByIdGreaterThan" method should find TxAbortedEvent.

2)  In method TxEventEnvelopeRepository.findStartedEventsWithMatchingEndedButNotCompensatedEvents, query SQL show by modified like this sql?
      SELECT t FROM TxEvent t 
      WHERE t.globalTxId = ?1 AND t.type = 'TxStartedEvent' AND EXISTS ( 
        SELECT t1.globalTxId
        FROM TxEvent t1 
        WHERE t1.globalTxId = ?1
        AND t1.localTxId = t.localTxId 
        AND t1.type = 'TxAbortedEvent'
      ) AND NOT EXISTS ( 
        SELECT t2.globalTxId
        FROM TxEvent t2 
        WHERE t2.globalTxId = 'ff66cf71-3562-41f7-9b42-2254954ec85b'
        AND t2.localTxId = t.localTxId 
        AND t2.type = 'TxCompensatedEvent') 
      ORDER BY t.surrogateId ASC

**Comment by coolbeevip** [comment]
After version 0.5.0, I suggest you use state machine mode instead of database mode

https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/fsm_manual.md

**Comment by WillemJiang** [comment]
current implementation based on database is not good enough for adding some sophisticated business logic, that is why we move to state machine implementation. 
In the below document, you can see the TxAbortedEvent can make the Transaction failed. 
https://github.com/apache/servicecomb-pack/blob/master/docs/fsm/design_fsm_zh.md

**Comment by WillemJiang** [comment]
@gjguanjie Do you have any further question about this issue?
