### ISSUE TITLE
分布式事务报错

### ISSUE THREAD

**Issue by tnessn** [apache/servicecomb-pack#640]
![image](https://user-images.githubusercontent.com/5991683/77494581-0d3a9100-6e81-11ea-8902-0749385e48cd.png)
请问下为什么偶尔会报这个错，然后服务调用不了，必须重启才能解决

**Comment by WillemJiang** [comment]
具体的问题是什么？可否提供相关的stack trace？
还有你使用的servicecomb-pack的版本是什么？

**Comment by tnessn** [comment]
> stack trace

版本是0.5.0

**Comment by tnessn** [comment]
![image](https://user-images.githubusercontent.com/5991683/77496311-a53a7980-6e85-11ea-9846-c69866adf11d.png)
用的是这种方式传上下文

**Comment by zhfeng** [comment]
那被调用的服务Service B是怎么样的呢？Transaction Id是如何propagated ？

**Comment by tnessn** [comment]
> 那被调用的服务Service B是怎么样的呢？Transaction Id是如何propagated ？
上面的日志就是被调用者的，调用者报请求超时，重启被调用者之后就正常

**Comment by tnessn** [comment]
> 那被调用的服务Service B是怎么样的呢？Transaction Id是如何propagated ？

上面的日志就是被调用者的，调用者报请求超时，重启被调用者之后就正常

**Comment by WillemJiang** [comment]
> ![image](https://user-images.githubusercontent.com/5991683/77496311-a53a7980-6e85-11ea-9846-c69866adf11d.png)
> 用的是这种方式传上下文

ServiceA是事务的起点吗？
看代码，我觉得ServiceA只是事务的参与者，这种情况下， ServiceA不应该用SagaStart标注啊！

**Comment by WillemJiang** [comment]
@tnessn 请问你的问题解决了吗？

**Comment by tnessn** [comment]
现在没出现，我怀疑是高并发导致的，后面再看看吧

**Comment by tnessn** [comment]
有一种情况被调用者需要重启，就是调用者注解使用错误的时候，我觉得这种情况不应该出现

**Comment by tnessn** [comment]
高并发的情况下，关闭服务，事务补偿好像没有执行到，想问下，这个该如何去处理

**Comment by WillemJiang** [comment]
> 有一种情况被调用者需要重启，就是调用者注解使用错误的时候，我觉得这种情况不应该出现

你开始附上的告警信息并不影响业务执行，只是这么把Alpha那端的事务追踪信息弄乱。调用者不应该需要重启。
我严重怀疑是你的调用端代码写的有问题，才需要重启。

**Comment by WillemJiang** [comment]
> 高并发的情况下，关闭服务，事务补偿好像没有执行到，想问下，这个该如何去处理

如果你的服务方代码标注有问题，业务不能回滚是正常的，因为你开启了一个新的Saga事务，新的事务和之前的Saga事务关系是脱开的。

**Comment by tnessn** [comment]
> > 有一种情况被调用者需要重启，就是调用者注解使用错误的时候，我觉得这种情况不应该出现
> 
> 你开始附上的告警信息并不影响业务执行，只是这么把Alpha那端的事务追踪信息弄乱。调用者不应该需要重启。
> 我严重怀疑是你的调用端代码写的有问题，才需要重启。

我说的被调用者是指provider，consumer的错误不应该影响到provider才对

**Comment by tnessn** [comment]
> > 有一种情况被调用者需要重启，就是调用者注解使用错误的时候，我觉得这种情况不应该出现
> 
> 你开始附上的告警信息并不影响业务执行，只是这么把Alpha那端的事务追踪信息弄乱。调用者不应该需要重启。
> 我严重怀疑是你的调用端代码写的有问题，才需要重启。

现在代码我觉得是没问题的，压测的时候，导致provider超时了，然后provider重启才能继续调用，目前这个问题还尚未解决
