### ISSUE TITLE
servicecomb支持spring，springboot1X，springboot2X吗？

### ISSUE THREAD

**Issue by god8816** [apache/servicecomb-pack#642]
servicecomb支持spring，springboot1X，springboot2X集成吗？是否可以给出demo方案

**Comment by WillemJiang** [comment]
ServiceComb 的项目很多，ServiceComb-Pack目前只支持 Spring Boot2。 
具体事例请参考 [此目录](https://github.com/apache/servicecomb-pack/tree/master/demo)下的工程
如果是询问ServiceComb-Java-Chassis的，请移步[至此提问](https://github.com/apache/servicecomb-java-chassis/issues)
