### ISSUE TITLE
globleID在子事务中为null，无法注册子事务。

### ISSUE THREAD

**Issue by tyronhui** [apache/servicecomb-pack#644]
我用的是0.5.0版本，feign调用服务。在子事务中获取omegaContext，其globalTxId获取不到。

**Comment by WillemJiang** [comment]
需要添加omega-transport-feign 依赖，建议你检查一下。

**Comment by tyronhui** [comment]
一直都已添加的。。但是感觉没什么用

**Comment by tyronhui** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sbc-service-fund</artifactId>
        <groupId>com.qlh</groupId>
        <version>1.17.0-RELEASE</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>service-fund-core</artifactId>

    <properties>
                <codingapi.txlcn.version>5.0.2.RELEASE</codingapi.txlcn.version>
        <codingapi.txlcn.qlh.version>5.0.2.RELEASE.QLH.0.0.1</codingapi.txlcn.qlh.version>
        <txlcn-org.springframework.cloud.commons.version>1.3.5.RELEASE</txlcn-org.springframework.cloud.commons.version>
        <saga.version>0.5.0</saga.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.35.Final</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-spring-starter</artifactId>
            <version>${saga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-spring-cloud-eureka-starter</artifactId>
            <version>${saga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-transport-feign</artifactId>
            <version>${saga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.3.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>jackson-databind</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.qlh</groupId>
            <artifactId>service-fund-api</artifactId>
            <version>1.17.0-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.qlh</groupId>
            <artifactId>service-fund-bean</artifactId>
            <version>1.17.0-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.wanmi.sbc</groupId>
            <artifactId>service-customer-api</artifactId>
            <version>1.17.0-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml</groupId>
            <artifactId>classmate</artifactId>
            <version>1.3.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.codingapi.txlcn</groupId>
		            <artifactId>txlcn-tc</artifactId>
            <version>${codingapi.txlcn.qlh.version}</version>
        </dependency>

        <dependency>
            <groupId>com.codingapi.txlcn</groupId>
            <artifactId>txlcn-txmsg-netty</artifactId>
            <version>${codingapi.txlcn.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.wanmi.sbc</groupId>
            <artifactId>service-marketing-api</artifactId>
            <version>1.17.0-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.wanmi.sbc</groupId>
            <artifactId>service-third-api</artifactId>
            <version>1.17.0-RELEASE</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>
</project>

**Comment by tyronhui** [comment]
> 需要添加omega-transport-feign 依赖，建议你检查一下。

<artifactId>service-fund-core</artifactId>

<properties>
            <codingapi.txlcn.version>5.0.2.RELEASE</codingapi.txlcn.version>
    <codingapi.txlcn.qlh.version>5.0.2.RELEASE.QLH.0.0.1</codingapi.txlcn.qlh.version>
    <txlcn-org.springframework.cloud.commons.version>1.3.5.RELEASE</txlcn-org.springframework.cloud.commons.version>
    <saga.version>0.5.0</saga.version>
</properties>

<dependencies>
    <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-all</artifactId>
        <version>4.1.35.Final</version>
    </dependency>
    <dependency>
        <groupId>org.apache.servicecomb.pack</groupId>
        <artifactId>omega-spring-starter</artifactId>
        <version>${saga.version}</version>
    </dependency>
    <dependency>
        <groupId>org.apache.servicecomb.pack</groupId>
        <artifactId>omega-spring-cloud-eureka-starter</artifactId>
        <version>${saga.version}</version>
    </dependency>
    <dependency>
        <groupId>org.apache.servicecomb.pack</groupId>
        <artifactId>omega-transport-feign</artifactId>
        <version>${saga.version}</version>
    </dependency>
    <dependency>
        <groupId>org.redisson</groupId>
        <artifactId>redisson</artifactId>
        <version>3.3.1</version>
        <exclusions>
            <exclusion>
                <artifactId>jackson-databind</artifactId>
                <groupId>com.fasterxml.jackson.core</groupId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>com.qlh</groupId>
        <artifactId>service-fund-api</artifactId>
        <version>1.17.0-RELEASE</version>
    </dependency>
    <dependency>
        <groupId>com.qlh</groupId>
        <artifactId>service-fund-bean</artifactId>
        <version>1.17.0-RELEASE</version>
    </dependency>
    <dependency>
        <groupId>com.wanmi.sbc</groupId>
        <artifactId>service-customer-api</artifactId>
        <version>1.17.0-RELEASE</version>
    </dependency>
    <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-cache</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
    </dependency>
    <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
    </dependency>
    <dependency>
        <groupId>com.fasterxml</groupId>
        <artifactId>classmate</artifactId>
        <version>1.3.1</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>org.apache.tomcat.embed</groupId>
        <artifactId>tomcat-embed-core</artifactId>
    </dependency>
    <dependency>
        <groupId>com.codingapi.txlcn</groupId>
	            <artifactId>txlcn-tc</artifactId>
        <version>${codingapi.txlcn.qlh.version}</version>
    </dependency>

    <dependency>
        <groupId>com.codingapi.txlcn</groupId>
        <artifactId>txlcn-txmsg-netty</artifactId>
        <version>${codingapi.txlcn.version}</version>
    </dependency>

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-amqp</artifactId>
    </dependency>
    <dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp</artifactId>
        <version>3.5.0</version>
    </dependency>
    <dependency>
        <groupId>com.wanmi.sbc</groupId>
        <artifactId>service-marketing-api</artifactId>
        <version>1.17.0-RELEASE</version>
    </dependency>
    <dependency>
        <groupId>com.wanmi.sbc</groupId>
        <artifactId>service-third-api</artifactId>
        <version>1.17.0-RELEASE</version>
        <scope>compile</scope>
    </dependency>

</dependencies>

**Comment by tyronhui** [comment]
> 需要添加omega-transport-feign 依赖，建议你检查一下。

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sbc-service-fund</artifactId>
        <groupId>com.qlh</groupId>
        <version>1.17.0-RELEASE</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>service-fund-core</artifactId>

    <properties>
                <codingapi.txlcn.version>5.0.2.RELEASE</codingapi.txlcn.version>
        <codingapi.txlcn.qlh.version>5.0.2.RELEASE.QLH.0.0.1</codingapi.txlcn.qlh.version>
        <txlcn-org.springframework.cloud.commons.version>1.3.5.RELEASE</txlcn-org.springframework.cloud.commons.version>
        <saga.version>0.5.0</saga.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.35.Final</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-spring-starter</artifactId>
            <version>${saga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-spring-cloud-eureka-starter</artifactId>
            <version>${saga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-transport-feign</artifactId>
            <version>${saga.version}</version>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>3.3.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>jackson-databind</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.qlh</groupId>
            <artifactId>service-fund-api</artifactId>
            <version>1.17.0-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.qlh</groupId>
            <artifactId>service-fund-bean</artifactId>
            <version>1.17.0-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.wanmi.sbc</groupId>
            <artifactId>service-customer-api</artifactId>
            <version>1.17.0-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml</groupId>
            <artifactId>classmate</artifactId>
            <version>1.3.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.codingapi.txlcn</groupId>
		            <artifactId>txlcn-tc</artifactId>
            <version>${codingapi.txlcn.qlh.version}</version>
        </dependency>

        <dependency>
            <groupId>com.codingapi.txlcn</groupId>
            <artifactId>txlcn-txmsg-netty</artifactId>
            <version>${codingapi.txlcn.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.wanmi.sbc</groupId>
            <artifactId>service-marketing-api</artifactId>
            <version>1.17.0-RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.wanmi.sbc</groupId>
            <artifactId>service-third-api</artifactId>
            <version>1.17.0-RELEASE</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>
</project>

**Comment by WillemJiang** [comment]
这是服务的调用方的pom吗？你有定义@SagaStart吗？是怎么定义的。

**Comment by WillemJiang** [comment]
@tyronhui  你的问题解决了吗？有什么进展吗？
