### ISSUE TITLE
请问0.5.0版本是不是不支持spring-boot-1.*  ？？

### ISSUE THREAD

**Issue by tyronhui** [apache/servicecomb-pack#651]
麻烦大神能不能说明下为什么0.4.0里面有spring-boot-1.* 和spring-boot-2的区别。。0.5.0里面就没有了。。

**Comment by WillemJiang** [comment]
因为spring-boot-2与spring-boot-1.5的API接口变化比较大， 从0.5.0开始我们就不支持spring-boot-1.5.x了， spring-boot-2 是指spring-boot-2.x。
