### ISSUE TITLE
get globalTxId.

### ISSUE THREAD

**Issue by serpentdark** [apache/servicecomb-pack#652]
1. Can I get globalTxId in @SagaStart service A method?
2. Can I pass globalTxId to service B?

**Comment by coolbeevip** [comment]
> 1. Can I get globalTxId in @SagaStart service A method?

You can inject OmegaContext object in service A and use globalTxId method

> 2. Can I pass globalTxId to service B?

Omega will pass globalTxId to service B

**Comment by serpentdark** [comment]
How to get globalTxId in service A?
```java
@SagaStart
public void foo(BarCommand cmd) {
  TransactionContext localTxContext = omegaContext.getTransactionContext();
  someRpc.send(cmd, localTxContext);
}
```
On above, How to declare `omegaContext` and `someRpc` object?

**Comment by WillemJiang** [comment]
> How to get globalTxId in service A?
> 
> ```java
> @SagaStart
> public void foo(BarCommand cmd) {
>   TransactionContext localTxContext = omegaContext.getTransactionContext();
>   someRpc.send(cmd, localTxContext);
> }
> ```
> 
> On above, How to declare `omegaContext` and `someRpc` object?

omegaContext can be injected into the your service object if the service object is managed by Spring.
 ```
@Inject
OmegaContext omegaContext

```
someRpc is just for demo for calling the outside service.

**Comment by serpentdark** [comment]
![Capture](https://user-images.githubusercontent.com/4797159/80686803-85851980-8af3-11ea-87fb-57fa07e94fde.PNG)

I can't use `@Inject `.
What is package should import to project?

pom.xml
```
<dependency>
	<groupId>org.apache.servicecomb.pack</groupId>
	<artifactId>omega-spring-starter</artifactId>
	<version>0.5.0</version>
</dependency>
<dependency>
	<groupId>org.apache.servicecomb.pack</groupId>
	<artifactId>omega-transport-resttemplate</artifactId>
	<version>0.5.0</version>
</dependency>
```
