### ISSUE TITLE
saga使用问题，不一定是bug

### ISSUE THREAD

**Issue by gjguanjie** [apache/servicecomb-pack#658]
使用https://hub.docker.com/r/coolbeevip/servicecomb-pack中 docker-compose.yaml 方式启动标准镜像只包含 Alpha 服务。 含状态机了。
客户端中引入，使用restTemplate方式
<dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-spring-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb.pack</groupId>
            <artifactId>omega-transport-resttemplate</artifactId>
        </dependency>
		
测试如下 代码如下：
服务1：
@RestController
@RequestMapping("/saga")
public class SagaController {

    private static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());

    @Resource
    private RestTemplate template;

    @GetMapping("/start")
    @SagaStart
    public void start() {
        LOGGER.error("调服务");
        template.postForObject("http://localhost:9001/service/test",null,String.class);
    }
}	

服务2：
@RestController
@RequestMapping("service")
public class SagaServiceController {

    private static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().getClass());

    @Resource
    private SagaService sagaService;

    @PostMapping("test")
    public void test(){
        sagaService.test();
    }
}

@Service
public class SagaService {

    private static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().getClass());

    @Compensable(compensationMethod = "cancel")
    public void test() {
        int aa = 1;
        LOGGER.error("测试方法");
        int bb = 1/0;
    }

    public void cancel() {
        LOGGER.error("Cancel方法");
    }
}

当调用服务1接口http://localhost:9000/saga/start时，遇到服务2中报错，原则上，会调用cancel方法，但没有执行。
数据库中txevent也没有saga对应的数据。以前数据DB存数时，还有数据，不知道状态机时，为啥没有数据了？ 求解。
使用tcc时也有同样问题

@Participate(confirmMethod = "confirmTcc", cancelMethod = "cancelTcc")
    public void tccTest() {
        int aa = 1;
        LOGGER.error("测试方法");
    }
    public void confirmTcc() {
        LOGGER.error("confirmTcc方法");
        int bb = 1/0;
    }

    public void cancelTcc() {
        LOGGER.error("cancelTcc方法");
    }

在confirmTcc方法报错时，原则上会调用cancelTcc()方法，但实际也没有调用？
求解

**Comment by WillemJiang** [comment]
你这边调用的服务还是比较少，如果只是一个服务调用失败的，Saga， TCC都不会调用这个服务的恢复方法。 建议你可以看一下 https://servicecomb.apache.org/cn/docs/distributed-transaction-of-services-1 这篇文章。

**Comment by gjguanjie** [comment]
从原理上讲，应该与服务多与少没有关系吧？从架构上，或服务A作为入口，调用服务B时，B服务出错，服务B方法中使用@Compensable(compensationMethod = "cancel")，那应该就会执行Alpha反回调cancel.

**Comment by gjguanjie** [comment]
https://servicecomb.apache.org/cn/docs/distributed-transaction-of-services-1  这文章上，也没有讲，服务多与少问题吧，
另我试了，服务A调用服务B和服务C，仅服务C出问题，还是不出会现调用cancel方法。
那么，我就不会知道，调用服务深度要多少（或服务多少）才能使用。
原理上讲，即使是服务A调用服务B这样简单的服务，至少也分布式事务。

**Comment by coolbeevip** [comment]
Saga是一种补偿机制，您的场景中如果B失败了，那么Saga是无法在调用B的补偿方法的。这里有一个前提就是服务自身的事务性要依赖于服务本身。您的例子里服务B的test方法可以增加try-catch捕获异常，然后调用cancel方法。

如果此时B服务的test方法导致B服务本身崩溃，那么这种方式就无效了。不过如果你的test方法中是一个数据库操作，并启动了事务。此时test方法中操作的数据库是可以回滚的。

无论如何，分布式事务在使用的时候还是需要针对自己的场景考虑的。
