### ISSUE TITLE
SagaActor 事件处理顺序的问题

### ISSUE THREAD

**Issue by starShinning** [apache/servicecomb-pack#662]
所有收到的事件都会转到kafka/redis/memory中再继续消费，而在使用kafka和redis消费过程中并没有要求顺序执行，这样是否会造成由于消费顺序与事件本身的顺序不一致而导致状态异常？

**Comment by coolbeevip** [comment]
在Kafka 中是用 global_ID 做分区的，可以保证一个全局事务内的所有子事务消息是有序消费的

**Comment by starShinning** [comment]
也就是redis目前没有强制顺序消费？

**Comment by starShinning** [comment]
还有一个问题，在补偿过程中，如果需要对多个子事务进行补偿，目前只看到补偿执行的顺序是逆序，似乎没有看到 强制要求必须在上一个补偿成功以后再调用下一个补偿

**Comment by coolbeevip** [comment]
> 也就是redis目前没有强制顺序消费？

Redis 只是用于持久化 Akka Actor 的状态机信，当几个服务器崩溃后，未执行完毕的 Actor会在另外一台机器上读取Redis并能恢复这个状态机

**Comment by coolbeevip** [comment]
> 还有一个问题，在补偿过程中，如果需要对多个子事务进行补偿，目前只看到补偿执行的顺序是逆序，似乎没有看到 强制要求必须在上一个补偿成功以后再调用下一个补偿

补偿是逆序执行的，并且执行成功一个以后才会执行第二个。

**Comment by starShinning** [comment]
> > 还有一个问题，在补偿过程中，如果需要对多个子事务进行补偿，目前只看到补偿执行的顺序是逆序，似乎没有看到 强制要求必须在上一个补偿成功以后再调用下一个补偿
> 
> 补偿是逆序执行的，并且执行成功一个以后才会执行第二个。

了解了，谢谢
