### ISSUE TITLE
调用@Compensable注解方法前没有调用@SagaStart注解的方法，会报nullpointsexception，导致连接不可用。

### ISSUE THREAD

**Issue by fengmingming** [apache/servicecomb-pack#663]
如果在调用@Compensable注解方法前没有调用@SagaStart注解的方法，会报nullpointerexception。这种情况下会执行以下代码
 LOG.error("Retry sending event {} due to failure", event, e);
 loadContext.getSenders().put(messageSender, Long.MAX_VALUE);
导致 messageSender 不可用。再次请求就会报all alpha server is down。
我看代码中有重连的逻辑，但不知道如何让重连逻辑起作用？
如果能把异常包装成omegaexception,就可用避免这个问题。问题代码如下
LoadBalanceSenderAdapter.java
AlphaResponse response = null;
    try {
      long startTime = System.nanoTime();
      response = executor.apply(event);
      loadContext.getSenders().put(messageSender, System.nanoTime() - startTime);
    } catch (OmegaException e) {
      throw e;
    } catch (Exception e) {
      LOG.error("Retry sending event {} due to failure", event, e);
      loadContext.getSenders().put(messageSender, Long.MAX_VALUE);//设置MAX_VALUE 导致messageSender不可用。
    }
    return Optional.fromNullable(response);

**Comment by coolbeevip** [comment]
这种情况应该会提示 Cannot find the globalTxId from OmegaContext 错误吧

https://github.com/apache/servicecomb-pack/blob/b476b8b7b98e3feafacfb26beafd78523176b83a/omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspect.java#L60

**Comment by fengmingming** [comment]
> 
> 
> 这种情况应该会提示 Cannot find the globalTxId from OmegaContext 错误吧
> 
> https://github.com/apache/servicecomb-pack/blob/b476b8b7b98e3feafacfb26beafd78523176b83a/omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspect.java#L60

看到在0.6.0中已经提示 Cannot find the globalTxId from OmegaContext
