### ISSUE TITLE
Alpha 端使用各种注册中心是做什么用的呢，默认使用consul，但是本地没有consul也能正常启动啊

### ISSUE THREAD

**Issue by starShinning** [apache/servicecomb-pack#664]

**Comment by coolbeevip** [comment]
通常情况不需要使用注册中心，因为 omega 可以通过地址直接链接 alpha

当你不想在 omega 配置多个 alpha 地址的时候，你可以将多个 alpha 注册到注册中心。然后在 omega 配这个注册中心地址，这样 omega 在启动的时候通过注册中心获取多个 alpha 的地址进行连接
