### ISSUE TITLE
是否支持网格，比如istio

### ISSUE THREAD

**Issue by pengyu0929** [apache/servicecomb-pack#670]
你好，我想咨询下，0.4版本是否支持网格；
如果支持的话，需要做什么配置吗？

**Comment by WillemJiang** [comment]
Pack底层会使用grpc来进行通讯，网格需要保证请求能够正确路由有到相关的实例就可以。 
如果你的应用实例在进行恢复的时候，能做到与实例无关，那直接使用网格就可以，如果恢复是绑定到具体实例的， 那么网格要保证请求路由到之前做业务的实例上。
