### ISSUE TITLE
扫描漏洞Agora.cgi

### ISSUE THREAD

**Issue by qufa** [apache/servicecomb-pack#672]
使用漏洞扫描工具对alpha-server扫描，出现该漏洞提示，是否可能是由于alpha-server的gui模块引入的呢？
![IMG_2659](https://user-images.githubusercontent.com/68358882/87614853-ca5c3c00-c743-11ea-857c-a76cbc579c01.jpg)

**Comment by coolbeevip** [comment]
有可能，你可以通过防火墙控制只允许某个IP才能访问 alpha ui

**Comment by WillemJiang** [comment]
Can we add some access control on the alpha-server side?

**Comment by coolbeevip** [comment]
> 使用漏洞扫描工具对alpha-server扫描，出现该漏洞提示，是否可能是由于alpha-server的gui模块引入的呢？
> ![IMG_2659](https://user-images.githubusercontent.com/68358882/87614853-ca5c3c00-c743-11ea-857c-a76cbc579c01.jpg)

这可能是一个误报，需要提供 Agora.cgi 的详细错误信息，也许是跨站脚本问题

**Comment by yfh1995** [comment]
题主有得出结论吗

**Comment by WillemJiang** [comment]
这应该是一个误报。
