### ISSUE TITLE
 servicecomb-pack支持注册到service center吗？

### ISSUE THREAD

**Issue by loringao** [apache/servicecomb-pack#676]
servicecomb-pack 注册中心支持里面居然没有 servicecenter 是不支持吗？

**Comment by WillemJiang** [comment]
servicecomb-pack  Alpha与Omega的通信选用的GRPC，没有使用Java Chassis，没有对ServiceCenter的强依赖。 
还有就是servicecomb-pack Alpha的服务信息注册是通过Spring Cloud提供的接口来实现的， 在ServiceCenter提供Spring Cloud集成的情况下，支持的工作量不大。

**Comment by loringao** [comment]
谢谢
