### ISSUE TITLE
支持rabbitmq

### ISSUE THREAD

**Issue by githubcheng2978** [apache/servicecomb-pack#686]
我这边因为不能使用redis和kafka作为消息队列，能否支持一下rabbitmq呢

**Comment by coolbeevip** [comment]
kafka作为消息队列，redis为akka的actor的分布式状态机提供状态存储。如果要替换这部分可能需要了解一下消息处理部分的逻辑，和akka的状态机持久化的配置

**Comment by githubcheng2978** [comment]
redis为akka的actor的分布式状态机提供状态存储，这个是以插件的方式提供的，也在源码里面看到了用到了redis和kafka，以及inmemory作为消息队列。 如果需要使用rabiitmq，我理解只需要在消息处理的逻辑里面，新增rabbitmq的支持就可以了。

**Comment by coolbeevip** [comment]
> redis为akka的actor的分布式状态机提供状态存储，这个是以插件的方式提供的，也在源码里面看到了用到了redis和kafka，以及inmemory作为消息队列。 如果需要使用rabiitmq，我理解只需要在消息处理的逻辑里面，新增rabbitmq的支持就可以了。

是的

**Comment by githubcheng2978** [comment]
我已经将rabbit的替代方案开发了，采用的spring-cloud-stream ，能否提PR

**Comment by coolbeevip** [comment]
> 我已经将rabbit的替代方案开发了，采用的spring-cloud-stream ，能否提PR

欢迎，最好是通过参数可以配置，这样使用者可以自行选择使用哪个方式
