### ISSUE TITLE
状态机模式是否有必要强依赖es

### ISSUE THREAD

**Issue by DawnSouther** [apache/servicecomb-pack#728]
servicecombo应该只是一个协调器，依赖es做历史记录查询是否有些太重了？
db查询的性能瓶颈在哪呢？把es做成一个可选项是一个更好的选择？

**Comment by coolbeevip** [comment]
Currently, only the state machine model uses ES to store archived messages and front-end queries. You can implement the TransactionRepository interface according to your favorite storage. Just like [ElasticsearchTransactionRepository.java](https://github.com/apache/servicecomb-pack/blob/master/alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/repository/elasticsearch/ElasticsearchTransactionRepository.java)

**Comment by DawnSouther** [comment]
I want to know why use ES in FSM? Is it just a temporary solution? Or what other considerations?

**Comment by coolbeevip** [comment]
ES is designed to provide an Improve query performance way to find and manage information on large transaction data
