### ISSUE TITLE
TCC模式 补偿方法执行了，但是ALpha还是会一直请求Registered TccEnded event,是为什么？还一直会往

### ISSUE THREAD

**Issue by yechengchao** [apache/servicecomb-pack#756]
![image](https://user-images.githubusercontent.com/66306387/165889934-a632b03a-49b2-4979-8e23-ffe889e83f7b.png)
![Uploading image.png…]()
补偿方法成功执行了，还一直往tcc_tx_event表里面插END_TIMEOUT的数据

**Comment by yechengchao** [comment]
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/66306387/165890539-5679d160-dd9c-4020-be14-9a397f61979a.png">

**Comment by WillemJiang** [comment]
Saga事务执行结束模块出错了，一般来说这里是不应该抛出问题的。

**Comment by yechengchao** [comment]
> Saga事务执行结束模块出错了，一般来说这里是不应该抛出问题的。

这不是Tcc吗

**Comment by WillemJiang** [comment]
不好意思，之前回复的时候没有注意上下文， 能把你的代码贴一下吗?
另外这篇文章也把详细的执行流程列出来了  https://servicecomb.apache.org/cn/docs/distributed-transaction-of-services-2/

**Comment by yechengchao** [comment]
> 不好意思，之前回复的时候没有注意上下文， 能把你的代码贴一下吗? 另外这篇文章也把详细的执行流程列出来了 https://servicecomb.apache.org/cn/docs/distributed-transaction-of-services-2/

A服务组合调用B和C服务：
![image](https://user-images.githubusercontent.com/66306387/167233363-68c2eafb-3738-43f0-88b0-bbbb8b68c180.png)
B服务：
![image](https://user-images.githubusercontent.com/66306387/167233375-40126a33-d5ba-465d-86f1-1c58315e2766.png)
C服务：
![image](https://user-images.githubusercontent.com/66306387/167233383-03f6491f-9512-4f47-92fe-97ac540f4020.png)

**Comment by WillemJiang** [comment]
刚刚看了一下代码， 发现这是一个bug， 定时监听程序没有处理好全局事务，我建了一个[JIRA](https://issues.apache.org/jira/browse/SCB-2484)来追踪这个问题。

**Comment by yechengchao** [comment]
> 刚刚看了一下代码， 发现这是一个bug， 定时监听程序没有处理好全局事务，我建了一个[JIRA](https://issues.apache.org/jira/browse/SCB-2484)来追踪这个问题。 对了，我还需要看一下GlobalTxEvent 这张表里面的内容。
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/66306387/168220796-633de1e7-d64b-45ff-85b3-e1e6fb2ce937.png">

**Comment by yechengchao** [comment]
> > 刚刚看了一下代码， 发现这是一个bug， 定时监听程序没有处理好全局事务，我建了一个[JIRA](https://issues.apache.org/jira/browse/SCB-2484)来追踪这个问题。 对了，我还需要看一下GlobalTxEvent 这张表里面的内容。
> 
> <img alt="image" width="1127" src="https://user-images.githubusercontent.com/66306387/168220796-633de1e7-d64b-45ff-85b3-e1e6fb2ce937.png">
