### ISSUE TITLE
org.apache.servicecomb.pack:pack:0.7.0-SNAPSHOT Errors: bad version: expected='0.7.0' found='0.7.0-SNAPSHOT'

### ISSUE THREAD

**Issue by wangjianglin** [apache/servicecomb-pack#763]
maven 仓库中 org.apache.servicecomb.pack:pack:0.7.0 版本不对，如下图：
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/8149579/180614809-fb2ba9fd-4313-4fda-90f5-03cefca2262c.png">

**Comment by coolbeevip** [comment]
Thank you for reporting this issue. I'll make 0.7.1 version to fix this issue

**Comment by coolbeevip** [comment]
This issue resolved in 0.7.1 release
